# -*- coding: utf-8 -*-
"""Batch 2: NUM ore petrology, Mireslab 2023 drill-core reports, Khanlab O-24 OVD009, ARDH-2005-01 stubs."""
import json, os

OUT = os.path.dirname(os.path.abspath(__file__))

def R(**kw):
    rec = {
        "source_file": None, "source_fileId": None, "sample_id": None,
        "drillhole_id": None, "depth": None, "sample_type": None,
        "rock_name": None, "rock_name_original": None, "texture": None,
        "minerals": [], "alteration": None, "opaque_minerals": None,
        "description_summary": None, "analyst_or_lab": None, "report_date": None,
    }
    rec.update(kw)
    return rec

recs = []

# ================================================================ A (cont.) NUM ore petrology
SF = "BE-3 samples in English.pdf (Results of Ore Petrology - Ragnarock Investment, 3 block samples)"
FID = "1JCorsOW4v8Vepb9HJlzYNDtzabENxU25"
LAB = "L. Oyunjargal Ph.D (NUM); client Ragnarock Investment LLC; 9-page report. Mongolian-language twin: 'BE-3 samples in Mongolian.pdf' fileId 1POBc4Or0a4L_m33xSjb5WwJSULy7bb0X"
DT = "2023-06-22"
recs.append(R(source_file=SF, source_fileId=FID, sample_id="40763", drillhole_id="OVD008 (per ABM 'Suggested Petro for the Oval 2024' list)", depth="84.5 m (per ABM list; not stated in this report)",
    sample_type="polished block sample (ore petrology / reflected light)",
    rock_name=None,
    texture="Structure and texture: disseminated, veinlets. Opaque grain size 11-5155 um; ore vein width 6-38 um. Rock = 20-25% ore minerals, 75-80% gangue",
    minerals=[{"mineral":"Pyrrhotite (tabulated as 'Pyrite')","pct":"10-15"},{"mineral":"Chalcopyrite","pct":"5"},
              {"mineral":"Pentlandite","pct":"2"},{"mineral":"Magnetite","pct":"3"}],
    alteration="Pyrrhotite partially altered to magnetite; pyrrhotite surfaces porous",
    opaque_minerals="Paragenetic sequence pyrrhotite -> chalcopyrite -> pentlandite -> magnetite. Pyrrhotite anhedral, whitish yellow, impure surface, 26-5155 um; chalcopyrite greenish-yellow anhedral 39-1810 um; pentlandite anhedral 35-388 um; magnetite grey anhedral 11-410 um micro-disseminated, plus vein-like accumulations 6-38 um along gangue cracks",
    description_summary="Polished block containing 20-25% ore minerals: anhedral disseminated pyrrhotite (whitish yellow, porous, up to 5155 um) rimmed by greenish-yellow chalcopyrite and partially altered to magnetite. Chalcopyrite (39-1810 um) is associated with pyrrhotite, pentlandite and magnetite; pentlandite (35-388 um) accompanies pyrrhotite and chalcopyrite. Grey magnetite is minor, micro-disseminated, and also forms vein-like accumulations 6-38 um wide along cracks in the gangue.",
    analyst_or_lab=LAB, report_date=DT))
recs.append(R(source_file=SF, source_fileId=FID, sample_id="40900", drillhole_id="OVD001 (per ABM 'Suggested Petro for the Oval 2024' list)", depth="56.8 m (per ABM list; not stated in this report)",
    sample_type="polished block sample (ore petrology / reflected light)",
    rock_name=None,
    texture="Structure and texture: disseminated, colloform. Opaque grain size 25-2300 um. Ore minerals about 5% of rock volume",
    minerals=[{"mineral":"Pyrite","pct":"<1"},{"mineral":"Native copper","pct":"<1"},
              {"mineral":"Goethite","pct":"5"},{"mineral":"Limonite","pct":"<1"}],
    alteration="Supergene - goethite altered to limonite; limonite as very fine earthy aggregates",
    opaque_minerals="Paragenetic sequence pyrite -> copper -> goethite -> limonite. Creamy yellow anhedral pyrite 34-304 um associated with gangue; two anhedral pink native-copper grains 92x210 and 83x110 um; goethite altering to limonite",
    description_summary="Polished block with about 5% ore minerals forming disseminated and colloform accumulations. Creamy yellow anhedral pyrite (34-304 um) sits with gangue minerals. Two grains of pink native copper (92x210 and 83x110 um) were found, anhedral under the ore microscope. Goethite alters to limonite, which is distributed through the rock as very fine earthy aggregates.",
    analyst_or_lab=LAB, report_date=DT))
recs.append(R(source_file=SF, source_fileId=FID, sample_id="40913", drillhole_id="OVD001 (per ABM 'Suggested Petro for the Oval 2024' list)", depth="68.0 m (per ABM list; not stated in this report)",
    sample_type="polished block sample (ore petrology / reflected light)",
    rock_name=None,
    texture="Structure and texture: disseminated, massive, veinlets. Opaque grain size 30-8649 um; ore vein width 17-221 um. Rock = 55% ore minerals, 45% non-ore",
    minerals=[{"mineral":"Pyrrhotite (tabulated as 'Pyrite')","pct":"30-35"},{"mineral":"Chalcopyrite","pct":"10-15"},
              {"mineral":"Cubanite (?)","pct":"5"},{"mineral":"Magnetite","pct":"2"},
              {"mineral":"Pentlandite (?)","pct":"3"}],
    alteration=None,
    opaque_minerals="Paragenetic sequence pyrrhotite -> chalcopyrite -> cubanite. Creamy yellow anhedral pyrrhotite 30-2710 um plus 17-221 um veinlets; greenish yellow anhedral chalcopyrite 108-8649 um; cubanite anhedral 56-400 um with pyrrhotite; pinkish-creamy pentlandite anhedral 21-265 um; magnetite as veinlets in gangue cracks",
    description_summary="Semi-massive sulphide block in which ore minerals make up 55% of the rock. Creamy yellow anhedral pyrrhotite (30-2710 um) dominates and also forms veinlets 17-221 um wide. Greenish yellow anhedral chalcopyrite reaches 8649 um. Cubanite (56-400 um) is associated with pyrrhotite grains, and pinkish-creamy pentlandite (21-265 um) accompanies pyrrhotite; magnetite occurs as veinlets in cracks in the gangue.",
    analyst_or_lab=LAB, report_date=DT))

# ================================================================ B  Report20231124.docx
SF = "Report20231124.docx"
FID = "106T7bR2o5_Pw1pFPEcfzml6Q9DhdnFUT"
LAB = "Mireslab Mongol LLC - Engineer Erdenebayar J, Ph.D; Director Batsumber A, M.Eng. Report #2303 / Order No 008 for Innova Mineral LLC (contact Batkhurel). 2 polished thin sections per sample prepared at MiReSLab Japan; Nikon Eclipse LV100NPOL; JEOL JSM 5400 SEM + Oxford EDS, Akita University"
DT = "2023-11-24"
recs.append(R(source_file=SF, source_fileId=FID, sample_id="40763", drillhole_id="OVD-008", depth="84.5 m",
    sample_type="polished thin section (x2) + SEM-EDS",
    rock_name=None,
    texture="Type-1 magmatic assemblage: interstitial inclusions and globular/ellipsoidal pentlandite-chalcopyrite-pyrrhotite intergrowths; flame-like pentlandite exsolution lamellae in pyrrhotite; angular interstitial sulphides",
    minerals=[{"mineral":"Nickel pyrrhotite","pct":"74-86 (of sulphide)"},{"mineral":"Chalcopyrite","pct":"9-20 (of sulphide)"},
              {"mineral":"Pentlandite","pct":"0.5-6 (of sulphide)"},{"mineral":"Pyrite","pct":None},
              {"mineral":"Goethite","pct":None},{"mineral":"Titanomagnetite","pct":None},
              {"mineral":"Magnetite","pct":None},{"mineral":"Chromium-alumina spinel","pct":None},
              {"mineral":"Ilmenite (Cr-bearing)","pct":None},{"mineral":"Galena","pct":"small amount"},
              {"mineral":"Zn-bearing mineral","pct":"small amount"},{"mineral":"Ag-Te mineral","pct":"unknown/trace"},
              {"mineral":"Ni-bearing anglesite","pct":"unknown/trace"}],
    alteration="Where the rocks have undergone significant metasomatism pyrite and chalcopyrite become dominant, but total sulphide is then small (generally <3-10%)",
    opaque_minerals="Sulphides: pyrrhotite (Ni-bearing), chalcopyrite, pentlandite, pyrite (Ni-bearing), goethite. Pentlandite carries about 1.2 wt% Co and 30.9-36.3% Ni; lamellar pentlandite (pn2) has lower Ni (20.9-28.3%) and very low Co (~0.3 wt%). Oxides: titanomagnetite, magnetite, Cr-Al spinel, Cr-bearing ilmenite",
    description_summary="Sample dominated by sulphides (pyrrhotite, chalcopyrite, pentlandite, pyrite, goethite) together with spinel-group minerals (titanomagnetite, magnetite, chromium-alumina spinel) and ilmenite. Nickel pyrrhotite makes up 74-86% of the sulphide assemblage, chalcopyrite 9-20% and pentlandite 0.5-6%. Early pentlandite (pn1) contains 30.9-36.3% Ni with about 1.2 wt% Co, whereas lamellar pentlandite (pn2) is poorer in Ni (20.9-28.3%) and nearly Co-free. SEM-EDS additionally detected minor galena, Zn-bearing minerals, Cr-bearing ilmenite and unknown Ag-Te and Ni-bearing anglesite phases.",
    analyst_or_lab=LAB, report_date=DT))
recs.append(R(source_file=SF, source_fileId=FID, sample_id="40913", drillhole_id="OVD-001", depth="68 m",
    sample_type="polished thin section (x2) + SEM-EDS",
    rock_name=None,
    texture="Anhedral crystals of laminated pyrrhotite intergrown with chalcopyrite and pentlandite; magnetite segregations always at intergrowth margins; pyrite pseudomorphs after pyrrhotite and violarite after pentlandite; independent pyrite aggregates with residual marginal chalcopyrite",
    minerals=[{"mineral":"Pyrrhotite","pct":None},{"mineral":"Chalcopyrite","pct":None},
              {"mineral":"Pentlandite","pct":None},{"mineral":"Sphalerite","pct":"small amount"},
              {"mineral":"Cubanite","pct":"small amount"},{"mineral":"Argentopentlandite","pct":"small amount"},
              {"mineral":"Galena","pct":"small amount"},{"mineral":"Magnetite","pct":None},
              {"mineral":"Violarite (secondary)","pct":None},{"mineral":"Pyrite (secondary)","pct":None},
              {"mineral":"Sb-michenerite (PGM)","pct":"submicron"},{"mineral":"Ag-Te mineral","pct":"submicron"},
              {"mineral":"Ni-bearing anglesite","pct":"submicron"}],
    alteration="Relatively low degree of alteration for the primary Po-Ccp-Pn assemblage; hydrothermal replacement of pyrrhotite by pyrite and of pentlandite by violarite in the metasomatised parts",
    opaque_minerals="Po-Ccp-Pn intergrowths with marginal magnetite; secondary chalcopyrite-violarite-pyrite pseudomorphs with residual pentlandite and pyrrhotite; late vein-like and finely dispersed pyrite-chalcopyrite. Submicron platinum and palladium minerals detected within the sulphides",
    description_summary="Pyrrhotite-chalcopyrite-pentlandite assemblages occur in relatively weakly altered rock, with only small amounts of sphalerite, cubanite, argentopentlandite and galena; the intergrowths are always accompanied by small magnetite segregations at their margins. SEM-EDS detected submicron platinum and palladium mineral inclusions inside the sulphide phases, together with an Ag-Te mineral and Ni-bearing anglesite. The report distinguishes three sulphide assemblage types across the deposit: (1) primary magmatic Pn-Ccp-Po intergrowths with spinel-group minerals and ilmenite, (2) secondary chalcopyrite-violarite-pyrite pseudomorphs with residual pentlandite and pyrrhotite (releasing Sb-Pd michenerite), and (3) newly formed vein-like and finely dispersed pyrite-chalcopyrite aggregates without PGM.",
    analyst_or_lab=LAB, report_date=DT))

# ================================================================ B  Report_20230816 Part1 + Part2 (23 samples)
SF = "Report_20230816_Part1.pdf + Report_20230816_Part2.pdf"
FID = "1KLR39-VqsFSizHMIQk81Alv-HWZuslik + 1TEpS_kJCBV63jULDdND8Y7DZHfoEGHFH"
LAB = ("Mireslab Mongol LLC - Engineer Erdenebayar J, Ph.D; Director Batsumber A, M.Eng. Report #2302 / Order No 007 "
       "for Innova Mineral LLC (contact Batkhurel). 23 polished thin sections prepared at Mineral Resource Science "
       "Laboratory, Akita, Japan; Nikon Eclipse LV100NPOL optical microscope; JEOL JSM 5400 SEM + Oxford EDS, Akita University")
DT = "2023-08-16"

# (mireslab_code, tag, hole, depth, mineralization/rock note from Table 1, lithofacies, hand specimen,
#  texture, alteration, opaques list, minerals list, summary)
M = [
 ("OVD001","40579","OVD-004","36 m","spotted???","Amphibole micro-gabbro",
  "Dark gray to dark green; grayish-white wavy banded striations apparently agglomerated plagioclase",
  "Holocrystalline, slightly fine-grained plagioclase + amphibole; ophitic texture",
  "Weak sericite-chlorite alteration; plagioclase weakly sericitised",
  "Hematite 20-50 um anhedral, minor, in amphibole; pyrite 20-50 um anhedral, minor, in amphibole; chalcopyrite 10-80 um anhedral, rare, with amphibole",
  [{"mineral":"Plagioclase (100-500 um, euhedral-subhedral)","pct":None},
   {"mineral":"Amphibole (100-500 um, subhedral, intergrown with plagioclase)","pct":None},
   {"mineral":"Hematite","pct":None},{"mineral":"Pyrite","pct":None},{"mineral":"Chalcopyrite","pct":"rare"}],
  "Holocrystalline amphibole micro-gabbro of slightly fine-grained plagioclase and amphibole showing ophitic texture. Alteration is weak sericite-chlorite; plagioclase is weakly sericitised and amphibole is colourless in PPL with highest-order interference colours. Opaques are sparse: hematite and pyrite (20-50 um, anhedral) in amphibole and rare anhedral chalcopyrite 10-80 um. No SEM-EDS was performed."),
 ("OVD002","40605","OVD-004","91 m","spotted","Amphibole-Orthopyroxene micro-gabbro",
  "Dark green, somewhat fine-grained equigranular",
  "Holocrystalline, slightly fine-grained plagioclase + amphibole; euhedral plagioclase poikilitic with orthopyroxene inclusions; anhedral plagioclase fills space between amphibole and euhedral plagioclase",
  "Weak sericite-chlorite alteration; weak sericitisation at the boundary between euhedral and anhedral plagioclase; chlorite rare after amphibole and plagioclase",
  "Chalcopyrite - anhedral, rare, occurring in fracture-filling veins",
  [{"mineral":"Plagioclase (50-1000 um, euhedral-subhedral, poikilitic)","pct":None},
   {"mineral":"Amphibole / hornblende (100-500 um, dark brown to yellow in PPL)","pct":None},
   {"mineral":"Orthopyroxene (10-80 um, euhedral, enclosed in plagioclase)","pct":None},
   {"mineral":"Chlorite (secondary, rare)","pct":None},{"mineral":"Chalcopyrite","pct":"rare"}],
  "Dark green fine-grained equigranular holocrystalline micro-gabbro of plagioclase, hornblende and orthopyroxene. Euhedral plagioclase encloses orthopyroxene poikilitically, and anhedral plagioclase fills the interstices between amphibole and euhedral plagioclase, with weak sericitisation at their boundaries. Alteration is weak sericite-chlorite. The only sulphide seen is rare anhedral chalcopyrite filling fractures. No SEM-EDS."),
 ("OVD003","40574","OVD-004","28 m","weakly mineralized / oxidized gabbro","Oxidized Amphibole Gabbro",
  "Dark green to grayish-white; the grayish-white colour forms irregular patches 3-4 cm across",
  "Holocrystalline plagioclase + amphibole; recently altered with secondary goethite",
  "Middle sericite-chlorite alteration; plagioclase strongly clay(sericite)-altered; amphibole strongly clay-altered but identified by columnar habit and 120-degree cleavage",
  "Hematite 20-80 um subhedral, rare, in amphibole; chalcopyrite 100-200 um anhedral with goethite; goethite up to 2000 um anhedral, secondary, replacing amphibole and carrying Cu",
  [{"mineral":"Plagioclase (100-500 um)","pct":None},{"mineral":"Amphibole (200-1000 um)","pct":None},
   {"mineral":"Hematite","pct":None},{"mineral":"Chalcopyrite","pct":None},{"mineral":"Goethite (Cu-, Ni-, Co-bearing)","pct":None}],
  "Oxidised amphibole gabbro, dark green with irregular 3-4 cm grayish-white patches, holocrystalline and moderately sericite-chlorite altered. Both plagioclase and amphibole are strongly clay-altered; amphibole is recognised only from its columnar habit and 120-degree cleavage. Coarse secondary goethite (up to 2000 um) is interpreted to replace amphibole, and SEM-EDS shows that this goethite contains Ni and Co while the amphibole itself carries Cu (and Ni). Chalcopyrite (100-200 um) occurs with the goethite and rare subhedral hematite sits in amphibole."),
 ("OVD004","40635","OVD-005","53 m","disseminate gabbro","Amphibole micro-gabbro",
  "Black to dark green, often surrounded by grayish white; mafic minerals heterogeneous in size",
  "Holocrystalline, slightly fine-grained plagioclase + amphibole; amphibole with ophitic texture",
  "Illite-smectite alteration; abundant illite-smectite in plagioclase; chlorite and calcite common in amphibole; sericitisation of plagioclase",
  "Ilmenite 50-100 um anhedral intergranular to plagioclase and amphibole (SEM-EDS shows Mn-rich pyrophanite and Mn-free ilmenite components); chalcopyrite 10-200 um anhedral, 10 um refined grains inside ilmenite, often with Ni-bearing pyrrhotite; Ni-bearing pyrrhotite 50-800 um anhedral; Heideite(?) (Fe,Cr)1.15(Ti,Fe)2S4, 10 um, irregular with chalcopyrite in ilmenite",
  [{"mineral":"Plagioclase (100-500 um)","pct":None},{"mineral":"Amphibole / hornblende (50-500 um, light brown in PPL)","pct":None},
   {"mineral":"Ilmenite","pct":None},{"mineral":"Chalcopyrite","pct":None},{"mineral":"Ni-bearing pyrrhotite","pct":None},
   {"mineral":"Heideite (?) Fe-Ti-Cr sulphide","pct":None},{"mineral":"Illite-smectite (secondary)","pct":None},
   {"mineral":"Chlorite + calcite (secondary)","pct":None}],
  "Holocrystalline amphibole micro-gabbro with ophitic amphibole, altered to an illite-smectite assemblage with chlorite and calcite in the amphibole. Ilmenite (50-100 um) is intergranular between plagioclase and amphibole and SEM-EDS resolves two components in it: a Mn-rich pyrophanite part and a Mn-free ilmenite part. Chalcopyrite (10-200 um, and 10 um refined grains inside ilmenite) occurs with Ni-bearing pyrrhotite (50-800 um). A 10 um Fe-Ti-Cr sulphide interpreted as possible heideite occurs irregularly with chalcopyrite inside ilmenite."),
 ("OVD005","40645","OVD-005","71 m","weakly mineralized gabbro","Amphibole gabbro",
  "Dark green with heterogeneous light green streak-patches",
  "Holocrystalline, slightly fine-grained plagioclase + amphibole, amphibole often ophitic",
  "Partly sericite-calcite alteration in patchy form; chalcopyrite, pyrrhotite and pyrite are predominant in the altered patches; amphibole often chloritised",
  "Ilmenite 50-400 um anhedral in amphibole; chalcopyrite 10-80 um anhedral inside pyrrhotite; pyrite 10-500 um anhedral, SEM-EDS shows slight Ni (0.54 wt% Ni); pentlandite 1-10 um anhedral, rare, at the rim of pyrite as fracture-filling (SEM-EDS: 22.19 wt% Ni, 4.35 wt% Co)",
  [{"mineral":"Plagioclase (50-400 um)","pct":None},{"mineral":"Amphibole / hornblende (50-800 um)","pct":None},
   {"mineral":"Ilmenite","pct":None},{"mineral":"Chalcopyrite","pct":None},{"mineral":"Ni-bearing pyrite","pct":None},
   {"mineral":"Pentlandite","pct":None},{"mineral":"Chlorite (secondary)","pct":None},{"mineral":"Sericite + calcite (secondary)","pct":None}],
  "Dark green holocrystalline amphibole gabbro with ophitic amphibole and patchy sericite-calcite alteration; chalcopyrite, pyrrhotite and pyrite concentrate in the altered patches and amphibole is partly chloritised. Ilmenite (50-400 um) sits inside amphibole. SEM-EDS shows the pyrite carries slight Ni (0.54 wt%) and that rare 1-10 um pentlandite occurs as fracture-filling at pyrite rims with 22.19 wt% Ni and 4.35 wt% Co."),
 ("OVD006","40715","OVD-007","98.2 m","schist","Shale (weak schistosity)",
  "Dark, fine-grained",
  "Pelitic rock with prominent sedimentary texture; fine pyrite in harmony with the sedimentary layering",
  "Not altered",
  "Pyrite ~1 um anhedral distributed in harmony with the sedimentary structure, and ~5 um subhedral-anhedral pyrite forming 10-20 um veinlets; calcite veinlets cut the pyrite veinlets",
  [{"mineral":"Quartz (very fine-grained)","pct":None},{"mineral":"Feldspar (very fine-grained)","pct":None},
   {"mineral":"Clay mineral","pct":None},{"mineral":"Pyrite","pct":None},{"mineral":"Calcite (veinlets)","pct":None}],
  "Dark fine-grained shale of very fine quartz, feldspar and clay minerals with a prominent sedimentary texture and weak schistosity. It is unaltered. Very fine (~1 um) anhedral pyrite is distributed in harmony with the sedimentary structure, and coarser (~5 um) subhedral to anhedral pyrite forms 10-20 um veinlets, which are in turn cut by calcite veinlets. No SEM-EDS."),
 ("OVD007","40628","OVD-005","40.5 m","disseminate gabbro","Amphibole gabbro",
  "Dark, equigranular, with sulphide mineral patches up to 1 cm across",
  "Holocrystalline rock of plagioclase and amphibole; amphibole intergrown with plagioclase and possibly replaced by sulphides",
  "Partly substantial sericite-calcite alteration in patchy form; chalcopyrite, pyrrhotite and pyrite predominate in altered patches; plagioclase sericitised in core with albite rim",
  "Cr-bearing magnetite 50-100 um subhedral-anhedral with altered amphibole and chalcopyrite; chalcopyrite 10-80 um anhedral with Ni-bearing pyrite; pyrite 10-500 um anhedral, sometimes Ni-bearing (SEM-EDS 24.63 wt% Ni in one spot); pentlandite 1-10 um anhedral in chalcopyrite; Ag-Te mineral 1 um at the rim of chalcopyrite and pentlandite; Ni-bearing anglesite (?) ~3 um",
  [{"mineral":"Plagioclase (50-400 um, sericitised core, albite rim)","pct":None},
   {"mineral":"Amphibole / hornblende (50-800 um)","pct":None},{"mineral":"Cr-bearing magnetite","pct":None},
   {"mineral":"Chalcopyrite","pct":None},{"mineral":"Ni-bearing pyrite","pct":None},{"mineral":"Pentlandite","pct":None},
   {"mineral":"Ag-Te mineral","pct":"trace"},{"mineral":"Ni-bearing anglesite (?)","pct":"trace"}],
  "Dark equigranular holocrystalline amphibole gabbro carrying sulphide patches up to 1 cm. Plagioclase is sericitised in the core with an albite rim, and amphibole is intergrown with plagioclase and may be replaced by sulphides. Alteration is patchy but locally strong sericite-calcite, and chalcopyrite, pyrrhotite and pyrite concentrate in these patches. SEM-EDS identified Cr-bearing magnetite, Ni-bearing pyrite, pentlandite in chalcopyrite and 1 um Ag-Te grains at chalcopyrite/pentlandite rims, plus a possible Ni-bearing anglesite."),
 ("OVD008","40530","OVD-003","157.5 m","disseminate gabbro","Amphibole micro-gabbro",
  "Dark black with thin dark green patchy distribution",
  "Holocrystalline rock of plagioclase and amphibole; holocrystalline and ophitic texture",
  "Partly strong sericitisation; plagioclase partly sericitised, cores often replaced by chalcopyrite or pyrite, rims chloritised; amphibole partly chloritised. Locally strong sericite-calcite alteration in patches where chalcopyrite, pyrrhotite and Ni-bearing pyrite predominate",
  "Magnetite 50-100 um subhedral-anhedral in amphibole; pyrite 10-200 um anhedral, sometimes replacing plagioclase and amphibole, sometimes Ni-bearing (SEM-EDS 0.52 wt% Ni); pyrrhotite 100-2000 um anhedral; chalcopyrite 10-1000 um anhedral with Ni-bearing pyrite; pentlandite 1-10 um; Ag-Te-Bi mineral 1 um in chalcopyrite and pyrite; Ag-Au mineral 1 um in pyrite; Cd-bearing sphalerite",
  [{"mineral":"Plagioclase (50-400 um)","pct":None},{"mineral":"Amphibole / hornblende (50-800 um)","pct":None},
   {"mineral":"Magnetite","pct":None},{"mineral":"Ni-bearing pyrite","pct":None},{"mineral":"Pyrrhotite","pct":None},
   {"mineral":"Chalcopyrite","pct":None},{"mineral":"Pentlandite","pct":None},{"mineral":"Cd-bearing sphalerite","pct":None},
   {"mineral":"Ag-Te-Bi mineral","pct":"trace"},{"mineral":"Ag-Au mineral","pct":"trace"}],
  "Dark black holocrystalline amphibole micro-gabbro with ophitic texture and partly strong sericitisation; plagioclase cores are often replaced by chalcopyrite or pyrite while the rims are chloritised. Sulphides are relatively abundant: anhedral pyrrhotite up to 2000 um, chalcopyrite up to 1000 um, Ni-bearing pyrite (0.52 wt% Ni) and 1-10 um pentlandite. SEM-EDS also detected Cd-bearing sphalerite and 1 um precious-metal phases - an Ag-Te-Bi mineral in chalcopyrite and pyrite and an Ag-Au mineral in pyrite."),
 ("OVD009","40899","OVD-001","15.5 m","spotted / Schist","Pelitic rock (weak schistosity)",
  "Blackish-brown to brown, considered weathered",
  "Characteristic massive texture of muddy rock; very fine-grained quartz, feldspar and clay minerals",
  "No alteration, but quartz and goethite-quartz veinlets are present",
  "Goethite in 50-100 um wide goethite-quartz veinlets, often with voids",
  [{"mineral":"Quartz (very fine-grained)","pct":None},{"mineral":"Feldspar (very fine-grained)","pct":None},
   {"mineral":"Clay mineral","pct":None},{"mineral":"Goethite (veinlets)","pct":None}],
  "Weathered blackish-brown to brown pelitic rock with weak schistosity and the characteristic massive texture of a muddy rock, composed of very fine-grained quartz, feldspar and clay minerals. It is unaltered but is cut by quartz and goethite-quartz veinlets 50-100 um wide that often contain voids; goethite occurs in these veinlets together with quartz. No SEM-EDS."),
 ("OVD010","40901","OVD-002","20.4 m","oxidized gabbro","Oxidized Amphibole Gabbro",
  "Black to dark green with patchy orange oxidised parts",
  "Holocrystalline rock of plagioclase and hornblende, ophitic texture; late-stage alteration with secondary goethite",
  "Partly strong sericite and epidote alteration; plagioclase strongly altered to clay (sericite, rarely calcite); amphibole strongly altered to chlorite and epidote",
  "Chalcopyrite 100-200 um anhedral with goethite; goethite up to 2000 um anhedral, thought to replace chalcopyrite; pyrite present",
  [{"mineral":"Plagioclase (100-400 um)","pct":None},{"mineral":"Amphibole (100-2000 um)","pct":None},
   {"mineral":"Goethite (secondary)","pct":None},{"mineral":"Chalcopyrite","pct":None},{"mineral":"Pyrite","pct":None},
   {"mineral":"Epidote (secondary)","pct":None},{"mineral":"Calcite","pct":None}],
  "Black to dark green oxidised amphibole gabbro with patchy orange oxidised zones and ophitic texture. Plagioclase is strongly clay(sericite)-altered and amphibole strongly chlorite-epidote altered, so the crystals are recognised mainly from their columnar habit. Coarse anhedral goethite (up to 2000 um) is interpreted to have replaced chalcopyrite, and 100-200 um chalcopyrite still occurs with the goethite. Calcite and goethite-quartz veining is present. No SEM-EDS."),
 ("OVD011","40902","OVD-002","87.4 m","schist","Pelitic rock",
  "Dark gray with helminthic white calcite veins",
  "Characteristic massive texture of muddy rock, rarely with 200 um plagioclase crystal fragments; dissemination of pyrite and pyrrhotite",
  "No alteration",
  "Pyrite 1-200 um euhedral to anhedral as fine-grained aggregates or crystal fragments; pyrrhotite 1-10 um anhedral, rarely with the pyrite aggregates",
  [{"mineral":"Quartz (very fine-grained)","pct":None},{"mineral":"Feldspar (very fine-grained)","pct":None},
   {"mineral":"Clay mineral","pct":None},{"mineral":"Pyrite","pct":None},{"mineral":"Pyrrhotite","pct":None},
   {"mineral":"Calcite (veins)","pct":None}],
  "Dark gray unaltered pelitic rock cut by helminthic white calcite veins, with the massive texture typical of a muddy rock and rare 200 um relict plagioclase crystal fragments. It consists of very fine-grained quartz, feldspar and clay minerals. Pyrite (1-200 um, euhedral to anhedral) forms fine aggregates and crystal fragments, and rare 1-10 um anhedral pyrrhotite accompanies the pyrite aggregates. No SEM-EDS."),
 ("OVD012","40903","OVD-001","7.15 m","gossan","Gossan (iron oxide-calcite-quartz; original lithofacies not identified)",
  "Dark black to reddish copper coloured, massive; some texture cut by quartz veins",
  "Composed of goethite and calcite with calcite filling between the goethite; rare unknown Fe-Si hydroxide minerals",
  "Strongly oxidised",
  "Goethite (dominant), unknown Fe-Si hydroxide mineral, unknown Ag-I mineral 8 um present in goethite, calcite (with small Mg content)",
  [{"mineral":"Goethite","pct":None},{"mineral":"Calcite (small Mg content)","pct":None},{"mineral":"Quartz","pct":None},
   {"mineral":"Fe-Si hydroxide mineral (unknown)","pct":None},{"mineral":"Ag-I mineral (unknown, 8 um)","pct":"trace"}],
  "Strongly oxidised gossan, dark black to reddish copper coloured and massive, cut in places by quartz veins. It consists of goethite with calcite filling the interstices between goethite, plus rare unknown Fe-Si hydroxide minerals. The original lithofacies cannot be identified. SEM-EDS identified goethite, an Fe-Si hydroxide mineral, calcite with a small Mg content, and an 8 um unknown Ag-I mineral hosted in goethite."),
 ("OVD013","40904","OVD-002","44.2 m (Table 1). NOTE: the body text of both report parts repeats 'Tag: 40902, Depth 87.4 m' for OVD013, which duplicates OVD011 and is a transcription error; Table 1 of Part 1 gives 40904 / 44.2 m",
  "disseminate gabbro","Amphibole micro-Gabbro",
  "Dark green to black, equigranular; calcite veins often present",
  "Holocrystalline rock of plagioclase and amphibole; ophitic texture not common in amphibole",
  "Middle sericite-chlorite alteration with chalcopyrite-pyrite veinlets; amphibole strongly chlorite-altered",
  "Magnetite 50 um subhedral-anhedral in amphibole; pyrite in chalcopyrite-pyrrhotite veinlets, anhedral, sometimes Ni-bearing (SEM-EDS 0.36 wt% Ni); pyrrhotite in chalcopyrite veinlets; chalcopyrite anhedral in veinlets with pyrite or Ni-bearing pyrite; pentlandite 1-10 um anhedral inside pyrite (SEM-EDS spot with 2.54 wt% Co); unknown As-Ag-Te sulphide mineral 1 um",
  [{"mineral":"Plagioclase (50-200 um)","pct":None},{"mineral":"Amphibole / hornblende (50-500 um)","pct":None},
   {"mineral":"Magnetite","pct":None},{"mineral":"Ni-bearing pyrite","pct":None},{"mineral":"Pyrrhotite","pct":None},
   {"mineral":"Chalcopyrite","pct":None},{"mineral":"Pentlandite","pct":None},
   {"mineral":"As-Ag-Te sulphide (unknown)","pct":"trace"},{"mineral":"Chlorite (secondary)","pct":None},{"mineral":"Calcite","pct":None}],
  "Dark green to black equigranular holocrystalline amphibole micro-gabbro with common calcite veins and moderate sericite-chlorite alteration; the amphibole is strongly chloritised. The distinctive feature is a chalcopyrite-pyrite(-pyrrhotite) veinlet. SEM-EDS identified chalcopyrite, pyrite, Ni-bearing pyrite (0.36 wt% Ni), pentlandite hosted in pyrite and an unknown 1 um As-Ag-Te sulphide."),
 ("OVD014","40905","OVD-001","35.8 m","spotted","Strong altered diabase",
  "Brown to light green, dense, no igneous texture determinable",
  "Very little discernible texture remains; goethite with slightly columnar shape around sericitised plagioclase gives a presumed ophitic-like texture; anorthite retained its shape better than the mafic minerals",
  "Strong sericite alteration; plagioclase strongly sericitised, mafic minerals and/or matrix oxidised; calcite and goethite veinlets present",
  "Goethite present as a replaced mafic mineral, often in veins; calcite in fractures or veinlets; other opaque minerals could not be confirmed",
  [{"mineral":"Altered plagioclase (50-300 um)","pct":None},{"mineral":"Goethite (after mafic mineral)","pct":None},
   {"mineral":"Calcite","pct":None}],
  "Dense brown to light green strongly altered diabase in which almost no igneous texture survives. Goethite with a slightly columnar habit surrounds sericitised plagioclase, giving a presumed relict ophitic texture, and the plagioclase (anorthite) has kept its shape better than the mafic minerals because of its greater resistance to alteration. Alteration is strong sericitisation of plagioclase with oxidation of the mafic minerals and matrix; calcite and goethite veinlets are present. No other opaque minerals could be confirmed and no SEM-EDS was done."),
 ("OVD015","40906","OVD-002","126.4 m","pyrite schist","Black Schist",
  "Black, massive; thin grayish-white patchy areas often arranged in lines",
  "Slightly sandy quartz, feldspar and clay minerals (chlorite, illite-smectite) with schistosity; ~50 um grains; weak boudinage and fold texture; sub-rounded to rounded clusters of coarser fragments produce the spotted appearance",
  "No alteration; quartz and goethite-quartz veinlets present, sometimes calcite and pyrite veinlets cutting the sedimentary and schistosity texture",
  "Hematite 100-500 um anhedral, rarely in clusters; pyrite 1-100 um euhedral to anhedral, commonly as veinlets",
  [{"mineral":"Quartz (~50 um)","pct":None},{"mineral":"Feldspar","pct":None},
   {"mineral":"Clay minerals (chlorite, illite-smectite)","pct":None},{"mineral":"Hematite","pct":None},
   {"mineral":"Pyrite","pct":None},{"mineral":"Calcite (veinlets)","pct":None}],
  "Black massive schist of slightly sandy quartz, feldspar and clay minerals (chlorite, illite-smectite) with schistosity, weak boudinage and fold textures. The spotted appearance in hand specimen reflects sub-rounded to rounded clusters of slightly coarser crystal fragments. The rock is unaltered but carries quartz and goethite-quartz veinlets, with calcite and pyrite veinlets locally cutting the sedimentary and schistose fabric. Opaques are anhedral hematite (100-500 um, rarely clustered) and common pyrite (1-100 um) as veinlets."),
 ("OVD016","40907","OVD-001","62.4 m","pyrite schist","Strong altered diabase",
  "Dark gray to dark green, irregularly distributed colours",
  "Very little discernible texture remains; goethite with slightly columnar shape around sericitised plagioclase gives presumed ophitic-like texture",
  "Strong sericite-calcite alteration; plagioclase strongly sericitised and calcite-altered; mafic minerals and matrix oxidised; calcite and goethite veinlets present",
  "Goethite present as a displaced mafic mineral, often in veins; calcite replacing plagioclase, often fractured or veined; pyrite 10-100 um euhedral to subhedral, commonly disseminated",
  [{"mineral":"Altered plagioclase (50-200 um)","pct":None},{"mineral":"Goethite (after mafic mineral)","pct":None},
   {"mineral":"Calcite","pct":None},{"mineral":"Pyrite","pct":None}],
  "Dark gray to dark green strongly altered diabase with irregular colour distribution and almost no preserved primary texture; a relict ophitic-like fabric is inferred from columnar goethite around sericitised plagioclase. Alteration is strong sericite-calcite: plagioclase is strongly sericitised and replaced by calcite, and the mafic minerals and matrix are oxidised. Calcite and goethite veinlets are present, and euhedral to subhedral pyrite 10-100 um is commonly disseminated. No SEM-EDS."),
 ("OVD017","40908","OVD-001","8.6 m","Cu-enriched, malachite","Gossan (copper-iron-oxide; original lithofacies not identified)",
  "Dark red patches with bright green copper oxide filling the cracks",
  "Copper-iron oxide mineral and malachite; malachite as fracture filling in goethite and Cu-Fe oxide; Fe-Si hydroxide mineral with brown rim and dark brown core",
  "Oxidised",
  "Malachite, goethite, Cu- and Ni-bearing Fe-Si hydroxide minerals (SEM-EDS shows the Fe-Si hydroxide rim contains Cu and Ni)",
  [{"mineral":"Goethite","pct":None},{"mineral":"Malachite","pct":None},
   {"mineral":"Copper-iron oxide mineral","pct":None},{"mineral":"Cu- and Ni-bearing Fe-Si hydroxide (unknown)","pct":None},
   {"mineral":"Quartz-clay mineral","pct":None},{"mineral":"Calcite (in altered plagioclase)","pct":None}],
  "Copper-iron-oxide gossan with dark red patches and bright green copper oxide filling cracks; the original lithofacies cannot be identified. Malachite is developed as fracture filling within goethite and copper-iron oxide minerals. An unknown Fe-Si hydroxide mineral with a brown rim and dark brown core occurs at the boundary between goethite and Cu oxide, and SEM-EDS shows that its rim contains both Cu and Ni."),
 ("OVD018","40909","OVD-002","51.6 m","schist?","Amphibole micro-gabbro",
  "Green to dark greenish-gray, fine-grained equigranular",
  "Holocrystalline rock of slightly fine-grained plagioclase and amphibole; amphibole intergrown with plagioclase",
  "Chlorite alteration; plagioclase weakly sericitised",
  "Chalcopyrite 50-100 um anhedral, rare, occurring with amphibole",
  [{"mineral":"Plagioclase (10-300 um)","pct":None},{"mineral":"Amphibole (10-500 um)","pct":None},
   {"mineral":"Chlorite (secondary)","pct":None},{"mineral":"Chalcopyrite","pct":"rare"}],
  "Green to dark greenish-gray fine-grained equigranular holocrystalline amphibole micro-gabbro. Plagioclase (10-300 um) is weakly sericitised and amphibole (10-500 um) is intergrown with it; the rock carries a chlorite alteration overprint. The only opaque phase observed is rare anhedral chalcopyrite (50-100 um) associated with amphibole. No SEM-EDS."),
 ("OVD019","40910","OVD-002","37 m","disseminate gabbro","Amphibole gabbro",
  "Black to dark greenish-gray, fine-grained equigranular; sulphide minerals irregularly scattered",
  "Holocrystalline rock of slightly fine-grained plagioclase and amphibole; amphibole often ophitic",
  "Partly sericitisation; sulphides sit in patchy strongly altered parts, with strong sericitisation between sulphide and rock-forming minerals; strongly sericitised amphibole may be actinolite",
  "Magnetite 50-100 um subhedral-anhedral in amphibole; chalcopyrite 10-1000 um anhedral with Ni-bearing pyrrhotite; pyrrhotite 10-200 um anhedral, Ni-bearing (SEM-EDS 0.57 wt% Ni); pyrite 10-200 um anhedral with Ni-bearing pyrrhotite; Ag-Te-Bi mineral and Ag-Te mineral, 1 um, rare, in chalcopyrite",
  [{"mineral":"Plagioclase (50-400 um)","pct":None},{"mineral":"Amphibole / hornblende (50-800 um)","pct":None},
   {"mineral":"Magnetite","pct":None},{"mineral":"Chalcopyrite","pct":None},{"mineral":"Ni-bearing pyrrhotite","pct":None},
   {"mineral":"Pyrite","pct":None},{"mineral":"Ag-Te-Bi mineral","pct":"trace"},{"mineral":"Ag-Te mineral","pct":"trace"}],
  "Black to dark greenish-gray fine-grained equigranular holocrystalline amphibole gabbro with often ophitic amphibole and irregularly scattered sulphides. Sericitisation is patchy and is strongest between the sulphides and the rock-forming minerals; strongly sericitised amphibole may in fact be actinolite. Chalcopyrite reaches 1000 um and occurs with Ni-bearing pyrrhotite (0.57 wt% Ni) and pyrite. SEM-EDS also detected rare 1 um Ag-Te and Ag-Te-Bi minerals inside the chalcopyrite."),
 ("OVD020","40911","OVD-002","75.5 m","spotted","Strong altered diabase",
  None,
  "Very little discernible texture remains; the spotted appearance is thought to be plagioclase or mafic minerals; more patchy and less basal area suggests a hypabyssal rather than holocrystalline rock, hence diabase",
  "Strong sericite-calcite alteration; plagioclase, mafic minerals and matrix strongly sericitised; calcite and pyrite veinlets present",
  "Pyrite 10-100 um euhedral to subhedral, disseminated and rarely as veinlets; calcite displaces plagioclase and mafic minerals, often fractured and veined",
  [{"mineral":"Altered plagioclase (50-200 um)","pct":None},{"mineral":"Calcite","pct":None},{"mineral":"Pyrite","pct":None}],
  "Strongly altered diabase in which very little discernible texture survives; the spotted appearance is interpreted as relict plagioclase or mafic minerals and the patchy, low-groundmass character suggests a hypabyssal rock. Alteration is strong sericite-calcite affecting plagioclase, mafic minerals and matrix alike, and calcite displaces plagioclase and mafic minerals and forms fractures and veins. Euhedral to subhedral pyrite (10-100 um) is disseminated and rarely forms veinlets. No SEM-EDS."),
 ("OVD021","40912","OVD-002","137.6 m (Table 1); body text of both parts gives 137.4 m","schist?","Black Schist (weak schistosity)",
  "Black to dark green with irregular lamination or cross-bedding-like texture",
  "Composed of fine-grained quartz, feldspar and clay minerals with weak schistosity",
  "Weak alteration",
  "Pyrite 1-500 um anhedral, disseminated or fissure-filling, cutting through the host-rock structure; no opaque minerals other than pyrite were found",
  [{"mineral":"Quartz (fine-grained)","pct":None},{"mineral":"Feldspar","pct":None},
   {"mineral":"Clay minerals","pct":None},{"mineral":"Pyrite","pct":None}],
  "Black to dark green weakly schistose black schist with an irregular lamination or cross-bedding-like texture, composed of fine-grained quartz, feldspar and clay minerals. Alteration is weak. Pyrite (1-500 um, anhedral) is the only opaque mineral present and occurs disseminated or as fissure fillings that cut through the host-rock structure. No SEM-EDS."),
 ("OVD022","40914","OVD-001","9.4 m","Cu-enriched, bornite gossan","Gossan (iron-copper oxide; altered gabbro?)",
  "Brown to reddish brown with scattered bright greenish copper oxide surrounded by greenish yellow",
  "Primarily quartz, goethite, Cu hydroxide mineral and clay minerals; quartz microstructure has a chalcedony texture filling voids; very rare relict textures presumed to be plagioclase or mafic mineral (amphibole?)",
  "Oxidised; intense oxidative action leaving very little original texture",
  "Cu hydroxide minerals 100-1000 um, disseminated, abundant, inferred to be malachite and atacamite from SEM-EDS; native copper 1-30 um encapsulated in Cu hydroxide mineral; goethite; Cu- and Ni-bearing Fe-Si hydroxide mineral",
  [{"mineral":"Quartz (chalcedonic)","pct":None},{"mineral":"Goethite","pct":None},
   {"mineral":"Malachite (Cu hydroxide)","pct":None},{"mineral":"Atacamite (Cu hydroxide)","pct":None},
   {"mineral":"Native copper","pct":None},{"mineral":"Cu- and Ni-bearing Fe-Si hydroxide","pct":None},
   {"mineral":"Clay minerals","pct":None}],
  "Intensely oxidised iron-copper oxide gossan, brown to reddish brown with scattered bright green copper oxide, in which very little original texture survives; rare relict textures presumed to be plagioclase or amphibole suggest the protolith was an altered, sulphide-bearing gabbro. It consists mainly of quartz (with chalcedonic void fill), goethite, Cu hydroxide minerals and clay minerals. SEM-EDS shows the abundant 100-1000 um Cu hydroxide minerals are malachite and atacamite, that 1-30 um native copper is encapsulated within them, and that the rim of an Fe-Si hydroxide mineral contains Cu and Ni."),
 ("OVD023","40915","OVD-009","72 m","disseminate gabbro","Altered Amphibole-Orthopyroxene micro-gabbro",
  "Dark black with pale yellow irregular patchy texture",
  "Presumed holocrystalline rock of relict plagioclase and mafic minerals; relict plagioclase has an ophitic-like texture",
  "Strong sericite-chlorite-epidote alteration; plagioclase core chloritised and rim sericitised; mafic mineral cores strongly chloritised and epidotised, rims sericitised. Gossan-like oxidised minerals could not be observed",
  "Cr-bearing magnetite 50 um euhedral-subhedral with mafic minerals; pentlandite 1-10 um anhedral in gaps between mafic crystals, often Co-bearing (SEM-EDS 31.41 wt% Ni, 2.06 wt% Co); chalcopyrite 30-300 um; pyrrhotite 30-300 um anhedral; pyrite 10-300 um anhedral, Ni-bearing (SEM-EDS 0.47 wt% Ni); galena 10-30 um anhedral with magnetite",
  [{"mineral":"Plagioclase (20-200 um, relict)","pct":None},{"mineral":"Mafic mineral - amphibole and/or pyroxene (30-900 um)","pct":None},
   {"mineral":"Cr-bearing magnetite","pct":None},{"mineral":"Pentlandite","pct":None},{"mineral":"Chalcopyrite","pct":None},
   {"mineral":"Pyrrhotite","pct":None},{"mineral":"Ni-bearing pyrite","pct":None},{"mineral":"Galena","pct":None}],
  "Dark black altered amphibole-orthopyroxene micro-gabbro with a pale yellow patchy texture, presumed holocrystalline with relict plagioclase showing an ophitic-like fabric. Alteration is strong sericite-chlorite-epidote: plagioclase cores are chloritised with sericitised rims, and the mafic mineral cores are strongly chloritised and epidotised. Chalcopyrite, pyrrhotite (30-300 um) and Ni-bearing pyrite occur in the interstices between strongly altered plagioclase and mafic crystals, in contact with the sericitisation rim. SEM-EDS identified Cr-bearing magnetite, Co-bearing pentlandite (31.41 wt% Ni, 2.06 wt% Co), Ni-bearing pyrite (0.47 wt% Ni) and galena with magnetite. No gossan-like oxidised minerals are present."),
]
for code, tag, hole, depth, note, litho, hand, tex, alt, opq, mins, summ in M:
    recs.append(R(source_file=SF, source_fileId=FID, sample_id=tag,
        drillhole_id=hole, depth=depth,
        sample_type="polished thin section; Mireslab internal sample code " + code +
                    (" ; hand specimen: " + hand if hand else "") +
                    " ; Table 1 note: " + note,
        rock_name=litho, rock_name_original=None, texture=tex,
        minerals=mins, alteration=alt, opaque_minerals=opq,
        description_summary=summ, analyst_or_lab=LAB, report_date=DT))

# ================================================================ C  Khanlab O-24, the 12 OVD009 samples
SF = "Petrography_mineragraphy_24 sample.pdf (consolidated 24-sample Khanlab O-24 report; per-sample PDFs 41014-41023, 41033, 41034 in folder 03_khanlab_Petrography_and_Mineralogy_description_2023)"
FID = "17L0euxdhc6dl-FDZchKX9xKrgYgvpKS3"
LAB = ("not stated in document (Khanlab, per ABM 'Suggested Petro for the Oval 2024' list); 'Петрографи, минераграфийн "
       "бичиглэл' format, sections numbered ӨТШ-<hole>-<depth>; Mongolian original also as 'Петрографи, минераграфи О -24.doc' "
       "and English translation 'Eng Петрографи, минераграфи О -24.doc'")
K = [
 ("41022","OVD009","11.3 m","1JizR826XY6q8ymy0RK9o9lDs5yXm-ag2 (n/a - see 41022.pdf 1RkwQDzRpOEVCEQKtoVRgbRJlaYn9JHnO)",
  "Altered gabbrodiorite porphyry","Хувирсан габбродиорит порфир",
  "Структур: шигтгээлэг, үнд.х-субофитлог, пойкилоофитлог, призмлэг мөхлөгт. Текстур: цул нягт. Шигтгээ 1.0-3.0 мм, үндсэн хэсэг 0.1-0.5 мм",
  [{"mineral":"Хувирсан плагиоклаз / altered plagioclase","pct":"60-65"},
   {"mineral":"Хувирсан эвэр хуурмаг / altered hornblende","pct":"20-25"},
   {"mineral":"Хувирсан биотит / altered biotite","pct":"10-15"},
   {"mineral":"Кварц / quartz","pct":"5-7"},
   {"mineral":"Ильменит / ilmenite","pct":"цөөн (few)"},
   {"mineral":"Гётит / goethite","pct":"ганц нэг (rare)"},
   {"mineral":"Гидрогётит / hydrogoethite","pct":"цөөн (few)"},
   {"mineral":"Хромит / chromite","pct":"цөөн (few)"},
   {"mineral":"Пирит / pyrite","pct":"ганц нэг (rare)"}],
  "Серицит, хлорит, актинолит, лейкоксен, серпентин; эпигенет карбонат, кварц. Плагиоклаз серицит, пелит, карбонатад хүчтэй хувирч зарим нь бүрэн псевдоморфоз болсон; эвэр хуурмаг хлорит-актинолитод, биотит карбонат, хлорит, лейкоксенд хувирсан; 0.5-1.0 мм өргөнтэй карбонат-кварцын судлууд",
  "Ильменит-хромит-пирит-гётит-гидрогётит. Ильменит саарал, изометрлэг 0.1-0.4 мм, хааяа лейкоксенжсэн; хромит бараан саарал 0.02-0.1 мм; гётит бүслүүрлэг 0.1-0.2 мм, захаасаа гидрогётитоор түрэгдсэн, дотор нь пиритын реликт; ан цаваар гидрогётит",
  "Плагиоклаз, хувирсан эвэр хуурмагийн шигтгээ маягийн ялгарлууд (40-45%) ба плагиоклаз, хувирсан эвэр хуурмаг, цөөвтөр биотит, кварцаас тогтсон субофитлог, пойкилоофитлог үндсэн хэсгээс бүрдэнэ. Плагиоклазын шигтгээ (1.0-2.5 мм) дундлаг-суурилаг найрлагатай, бүслүүрлэг, серицит-пелит-карбонатад хүчтэй хувирсан. Эвэр хуурмагийн шигтгээ хлорит-актинолитод хувирч хувирсан биотитоор түрэгдсэн; хувирсан биотитоор лейкоксенжсен рутил, сфен ялгарсан. Ойсон гэрэлд гётит, хромит, ильменит, пиритын цөөн мөхлөг тодорхойлогдов."),
 ("41019","OVD009","17.2 m","1CQ4503I4sAtUWB4e648LRlCQRP3XwYX5",
  "Porphyritic fine-grained pyroxene-hornblende gabbro (altered gabbro porphyry)",
  "Шигтгээ маягийн жижиг ширхэгтэй пироксен-эвэр хуурмагт габбро (Хувирсан габбро порфир)",
  "Структур: невадит шигтгээ маягийн, үнд.х-субофитлог, пойкилоофитлог, зарим хэсэгтээ микропегматитлаг. Текстур: цул нягт. Шигтгээ 1.0-3.0 мм, үндсэн хэсэг 0.1-0.8 мм",
  [{"mineral":"Хувирсан плагиоклаз / altered plagioclase (labradorite)","pct":"55-60"},
   {"mineral":"Эвэр хуурмаг / hornblende","pct":"35-40"},
   {"mineral":"Кварц / quartz","pct":"5-8"},
   {"mineral":"Мон.пироксен / clinopyroxene","pct":"цөөн (few)"},
   {"mineral":"Биотит / biotite","pct":"цөөн (few)"},
   {"mineral":"Апатит / apatite","pct":"цөөн (few)"},
   {"mineral":"Ильменит / ilmenite","pct":"цөөн (few)"},
   {"mineral":"Магнетит / magnetite","pct":"цөөн (few)"},
   {"mineral":"Пирит / pyrite","pct":"цөөн (few)"},
   {"mineral":"Хромит / chromite","pct":"цөөн (few)"},
   {"mineral":"Титанит / titanite","pct":"цөөн (few)"},
   {"mineral":"Халькопирит / chalcopyrite","pct":"ганц нэг (rare)"},
   {"mineral":"Ковеллин / covellite","pct":"ганц нэг (rare)"}],
  "Серицит, мусковит, соссюрит, хлорит, актинолит, карбонат, лейкоксен. Плагиоклаз серицит, мусковит, карбонат, соссюритад хүчтэй хувирсан; эвэр хуурмаг актинолитод бага зэрэг хувирсан; ан цаваар карбонатын линз, тасархай судланцар",
  "Ильменит-магнетит-хромит-титанит-пирит-халькопирит-ковеллин. Ильменит ягаавтар саарал, призмлэг 0.1-0.8 мм, хааяа лейкоксенжсэн; гематитад хувирсан магнетит 0.2-0.3 мм; хромит 0.03-0.1 мм; пирит 0.2-0.4 мм зөв хэлбэртэй, дотроо ковеллиноор түрэгдсэн халькопиритын бичил мөхлөг агуулна",
  "Эвэр хуурмагийн шигтгээ маягийн ялгарлууд (50-55%) ба плагиоклаз, эвэр хуурмаг, цөөн мон.пироксен, кварцаас тогтсон офитлог, пойкилоофитлог үндсэн хэсгээс бүрдэнэ. Эвэр хуурмагийн шигтгээ (1.0-3.0 мм) харьцангуй бага хувирсан, дотроо мон.пироксены 0.2-0.6 мм мөхлөг агуулна; мон.пироксен 36-38 градусын унтралтай, хувираагүй. Үндсэн хэсгийн плагиоклаз (0.2-0.8 мм) лабрадорын найрлагатай, серицит-мусковит-карбонат-соссюритад хүчтэй хувирсан. Кварц плагиоклазтай бичил пегматитлаг ургалт үүсгэнэ. Ойсон гэрэлд ильменит, магнетит, пирит, хромит тодорхойлогдож, пирит нь ковеллиноор түрэгдсэн халькопирит агуулна."),
 ("41018","OVD009","80.9 m (per section header; the ABM Khanlab sample sheet lists this interval as 80.8 m)","1Zfoebc7pNJtyTh3bEqcFkU9O2Pd-TXz2",
  "Porphyritic fine-grained pyroxene-hornblende gabbro (altered gabbro porphyry)",
  "Шигтгээ маягийн жижиг ширхэгтэй пироксен-эвэр хуурмагт габбро (Хувирсан габбро порфир)",
  "Структур: невадит шигтгээ маягийн, үнд.х-субофитлог, пойкилоофитлог. Текстур: цул нягт. Шигтгээ 1.0-3.5 мм, үндсэн хэсэг 0.1-0.6 мм",
  [{"mineral":"Хувирсан плагиоклаз / altered plagioclase","pct":"55-60"},
   {"mineral":"Эвэр хуурмаг / hornblende","pct":"35-40"},
   {"mineral":"Биотит / biotite","pct":"3-5"},
   {"mineral":"Мон.пироксен / clinopyroxene","pct":"цөөн (few)"},
   {"mineral":"Ильменит / ilmenite","pct":"цөөн (few)"},
   {"mineral":"Хромит / chromite","pct":"цөөн (few)"},
   {"mineral":"Пирит / pyrite","pct":"цөөн (few)"},
   {"mineral":"Титанит / titanite","pct":"цөөн (few)"},
   {"mineral":"Халькопирит / chalcopyrite","pct":"ганц нэг (rare)"}],
  "Серицит, соссюрит, хлорит, актинолит, карбонат, лейкоксен, тальк(?). Плагиоклаз серицит-карбонат-соссюритад хүчтэй хувирсан; үндсэн хэсгийн эвэр хуурмаг хлорит-актинолитот агрегатад хүчтэй хувирсан; ан цаваар карбонат",
  "Ильменит-хромит-титанит-пирит-халькопирит. Ильменит ягаавтар саарал 0.1-0.6 мм, хааяа лейкоксенжсэн; гематитад хувирсан магнетит 0.2-0.3 мм; хромит 0.03-0.1 мм; пирит 0.2-0.5 мм шигтгээлэг, хааяа халькопиритын бичил мөхлөг агуулна",
  "Энэ чулуу нь ерөнхийдөө OVD009-17.2 дээжтэй ижилхэн бөгөөд эвэр хуурмагийн шигтгээ маягийн ялгарлууд (50-55%) ба плагиоклаз, эвэр хуурмаг, цөөн мон.пироксеноос тогтсон офитлог, пойкилоофитлог үндсэн хэсгээс бүрдэнэ. Эвэр хуурмагийн шигтгээ (1.0-3.5 мм) бага хувирсан, дотроо хувираагүй мон.пироксены 0.2-0.5 мм мөхлөг агуулна. Актинолитын зүүлэг агрегат ба тальк(?)-ны бичил шөрмөслөг агрегатаас тогтсон псевдоморфозууд мон.пироксеноор үүссэн байх магадлалтай. Ойсон гэрэлд ильменит, магнетит, пирит, хромит, халькопиритын бичил шигтгээлэг мөхлөгүүд тодорхойлогдов."),
 ("41021","OVD009","126.7 m","1Sco5KPMthBmNCKDTM1HEyMb3ojskkA1N",
  "Schistose, carbonatised, strongly altered gabbrodiorite porphyry (metasomatite after gabbrodiorite)",
  "Занаржиж, карбонатчлагдаж, хүчтэй хувирсан габбродиорит порфир /Габбродиоритоор үүссэн метасоматит/",
  "Структур: реликт шигтгээлэг, үнд.х-реликт призмлэг мөхлөгт, микрогранолепидобласт. Текстур: занарлаг, линзлэг, судлархаг. Эрдсийн мөхлөг 0.01-1.0 мм",
  [{"mineral":"Хувирсан плагиоклаз / altered plagioclase","pct":"30-35"},
   {"mineral":"Серицит-хлоритын псевдоморфоз / sericite-chlorite pseudomorph","pct":"30-35"},
   {"mineral":"Титанит / titanite","pct":"1-3"},
   {"mineral":"Пирит / pyrite","pct":"цөөн (few)"},
   {"mineral":"Ильменит / ilmenite","pct":"ганц нэг (rare)"},
   {"mineral":"Мөнгө? / native silver (?)","pct":"1 ш (single grain)"},
   {"mineral":"Халькопирит / chalcopyrite","pct":"ганц нэг (rare)"},
   {"mineral":"Эпигенет карбонат / epigenetic carbonate","pct":"25-30"},
   {"mineral":"Эпигенет кварц / epigenetic quartz","pct":"5-10"}],
  "Хүчтэй метасоматоз: анхдагч габбродиорит порфир нэг зүг чиглэсэн альбит-хлоритоос тогтсон агрегатад хувирсан; плагиоклаз серицит, пелит, карбонатад хүчтэй хувирсан; лейкоксен, рутил; чулуу хүчтэй карбонатчлагдаж 0.1-2.0 мм өргөнтэй карбонатын линз, судлууд занаржилтын дагуу үүссэн",
  "Ильменит-пирит-титанит. Ильменит саарал 0.05-0.2 мм, томхон мөхлөгүүд хүчтэй лейкоксенжсэн; пирит 0.01-0.1 мм цөөн; лейкоксенжсэн титанит занаржилтын дагуу сунасан нарийхан линз, судланцар; тод цагаан өнгийн мөнгөний(?) 0.002 мм ганц нэг мөхлөг",
  "Анхдагч чулуу болох габбродиорит порфир (микрогаббродиорит) хүчтэй метасоматоз хувирлын улмаас нэг зүг чиглэсэн альбит-хлоритоос тогтсон агрегатад хувирч, реликт призмлэг мөхлөгт бүтцээ хадгалан үлджээ. Зарим хэсэгт плагиоклазын призмлэг мөхлөгүүд (0.1-0.8 мм) ба өнгөт эрдсээр (биотитоор?) үүссэн хлоритын псевдоморфозууд сайн хадгалагдсан. Хлорит нь 0.05-1.5 мм өргөнтэй линз, зурвасуудыг үүсгэнэ. Ойсон гэрэлд ильменит, пиритын бичил мөхлөгүүд ихэвчлэн хлоритоор үүссэн лейкоксенжсэн титанит дотор ялгарч үүссэн ба тод цагаан өнгийн мөнгөний ганц нэг бичил мөхлөг ажиглагдана."),
 ("41020","OVD009","143 m","1YsqkUicqDX6WJ5MLdGnSW87UC2_JchFX",
  "Mineralized porphyritic fine-grained hornblende-olivine-pyroxene melanocratic gabbro",
  "Хүдэржсэн шигтгээ маягийн жижиг ширхэгтэй эвэр хуурмаг-оливин-пироксент меланократ габбро",
  "Структур: габбро маягийн, субофитлог, пойкилоофитлог. Текстур: цул нягт, торлог, судлархаг. Шигтгээ 1.0-4.0 мм, үндсэн хэсэг 0.2-0.9 мм",
  [{"mineral":"Эвэр хуурмаг / hornblende","pct":"20-25"},
   {"mineral":"Мон.пироксен / clinopyroxene","pct":"15-20"},
   {"mineral":"Хувирсан плагиоклаз / altered plagioclase","pct":"20-25"},
   {"mineral":"Хувирсан оливин / altered olivine","pct":"15-20"},
   {"mineral":"Биотит / biotite","pct":"5-10"},
   {"mineral":"Пирротин / pyrrhotite","pct":"10-15"},
   {"mineral":"Халькопирит / chalcopyrite","pct":"3-5"},
   {"mineral":"Магнетит / magnetite","pct":"3-5"},
   {"mineral":"Ильменит / ilmenite","pct":"цөөн (few)"},
   {"mineral":"Пентландит / pentlandite","pct":"цөөн (few)"},
   {"mineral":"Хромит / chromite","pct":"цөөн (few)"}],
  "Серицит, иддингсит, биотит, серпентин, хлорит, актинолит, мусковит, тальк. Хувирсан оливин иддингсит(?), бастит-биотитод бүрэн хувирч серпентины нарийхан судлаар зүсэгдэн торлог бүтэц үүсгэсэн; плагиоклаз соссюрит, серицитэд хүчтэй хувирсан",
  "Ильменит-магнетит-пентландит-хромит-пирротин-халькопирит. Пирротин ягаавтар шаргал, изометрлэг 0.2-4.0 мм, халькопирит (0.2-1.5 мм) түүнийг түрж эмжээрлэсэн; линзүүд 0.5-4.5 мм; пентландит 0.1-0.5 мм пойкилитоор линз дотор; магнетит 0.2-0.8 мм шигтгээлэг ба серпентины судланцрын дагуу 0.01-0.1 мм; ильменит 0.1-0.9 мм; хромит 0.05-0.2 мм",
  "Өнгөт эрдсүүдийн шигтгээлэг ялгарлууд (50-55%) ба плагиоклаз, мон.пироксен, хувирсан биотит, эвэр хуурмагаас тогтсон офитлог, пойкилоофитлог, габбро маягийн үндсэн хэсгээс бүрдэнэ. Хувирсан оливины шигтгээ (1.5-4.0 мм) бор хүрэн иддингсит(?), бастит-биотитод бүрэн хувирч, серпентины судлуудаар зүсэгдэн торлог бүтэц үүсгэнэ. Мон.пироксены шигтгээ (1.1-3.0 мм) бараг хувираагүй, эвэр хуурмагийнх (1.0-3.5 мм) актинолитод бага хувирсан. Ойсон гэрэлд пирротин-халькопиритын ургалтаас тогтсон 0.5-4.5 мм линзүүд чулуунд жигд тархалттай үүссэн ба нүдээр ч ажиглагдана; линз дотор пентландитын зөв хэлбэртэй мөхлөгүүд пойкилитоор агуулагдана."),
 ("41015","OVD009","149.5 m","1EAtV1kmg-X0X6njWtMRP8cYUMUKTl5Za",
  "Altered gabbrodiorite porphyry (with hornblende gabbro schlieren)",
  "Хувирсан габбродиорит порфир",
  "Структур: шигтгээлэг, үнд.х-субофитлог, пойкилоофитлог, призмлэг мөхлөгт. Текстур: цул нягт. Шигтгээ 1.0-2.5 мм, үндсэн хэсэг 0.1-0.8 мм",
  [{"mineral":"Хувирсан плагиоклаз / altered plagioclase","pct":"75-80"},
   {"mineral":"Эвэр хуурмаг / hornblende","pct":"15-20"},
   {"mineral":"Кварц / quartz","pct":"цөөн (few)"},
   {"mineral":"Апатит / apatite","pct":"0.5-1"},
   {"mineral":"Ильменит / ilmenite","pct":"цөөн (few)"},
   {"mineral":"Пирит / pyrite","pct":"1-3"},
   {"mineral":"Титанит / titanite","pct":"цөөн (few)"},
   {"mineral":"Халькопирит / chalcopyrite","pct":"ганц нэг (rare)"}],
  "Серицит, карбонат, хлорит, актинолит, эпидот. Плагиоклазын шигтгээ эпидоттой мусковит-серицитэт агрегатад хүчтэй хувирч зарим нь бүрэн псевдоморфоз болсон; эвэр хуурмаг актинолит, карбонат, хлоритод хувирсан",
  "Ильменит-титанит-пирит-халькопирит. Пирит цайвар шар, зөв хэлбэртэй 0.1-0.6 мм шигтгээлэг, заримдаа бичил линз үүсгэнэ; ильменит ягаавтар саарал 0.1-0.4 мм, лейкоксеноор бага хувирсан; халькопирит 0.01-0.03 мм цөөн, хувирсан эвэр хуурмагтай ассоциацитай",
  "Хувирсан плагиоклазын шигтгээнүүд (10-15%) ба плагиоклаз, эвэр хуурмаг, цөөн кварцаас тогтсон офитлог, пойкилоофитлог үндсэн хэсгээс бүрдэнэ. Плагиоклазын шигтгээ (1.0-2.0 мм) бүслүүрлэг бүтэцтэй, эпидоттой мусковит-серицитэт агрегатад хүчтэй хувирсан. Үндсэн хэсгийн плагиоклаз (0.2-0.8 мм) шигтгээтэйгээ ижил, хэмжээгээрээ ялгаатай ба захын хэсэг нь хувираагүй. Энэ порфир дотор жижиг-дунд ширхэгтэй эвэр хуурмагт габбродиоритын 0.5-16 мм шлирүүд (15-20%) жигд тархалттай ажиглагдах ба тэдгээрт өнгөт эрдэстэй каркас маягийн ургалт үүсгэсэн титанит (ильменит) мөхлөгүүд, дотор нь халькопиритын бичил мөхлөгүүд ажиглагдана."),
 ("41033","OVD009","149.8 m","1a2lAdL9Zt_Y9CdFKSV8XuQtwK0GyDO3q",
  "Altered gabbro porphyry (with hornblende gabbrodiorite schlieren)",
  "Хувирсан габбро порфир",
  "Структур: шигтгээлэг, үнд.х-субофитлог, пойкилоофитлог, призмлэг мөхлөгт. Текстур: цул нягт. Шигтгээ 1.0-2.5 мм, үндсэн хэсэг 0.1-0.8 мм",
  [{"mineral":"Хувирсан плагиоклаз / altered plagioclase","pct":"50-55"},
   {"mineral":"Эвэр хуурмаг / hornblende","pct":"20-25"},
   {"mineral":"Мон.пироксен / clinopyroxene","pct":"10-15"},
   {"mineral":"Кварц / quartz","pct":"5"},
   {"mineral":"Ильменит / ilmenite","pct":"1-3"},
   {"mineral":"Пирит / pyrite","pct":"0.5"},
   {"mineral":"Титанит / titanite","pct":"цөөн (few)"},
   {"mineral":"Халькопирит / chalcopyrite","pct":"0.5-1.0"},
   {"mineral":"Апатит / apatite","pct":"цөөн (few)"}],
  "Серицит, карбонат, хлорит, актинолит, эпидот; эпигенет карбонат, кварц. Хувирсан эвэр хуурмагийн шигтгээ актинолит, хлоритод хүчтэй хувирсан; плагиоклазын шигтгээ эпидот, мусковит-серицитэт агрегатад хүчтэй хувирсан, захаараа хувираагүй эмжээртэй; 0.1-8.0 мм өргөнтэй кварц-карбонатын линз, судлууд",
  "Ильменит-титанит-пирит-халькопирит. Ильменит ягаавтар саарал, призмлэг 0.1-0.6 мм, лейкоксеноор бага хувирсан, халькопиритын 0.01-0.1 мм бичил мөхлөгтэй ургалт үүсгэнэ; кварц-карбонатын судал дотор пирит (0.1-0.6 мм) ба халькопирит (0.1-0.5 мм) линзлэг ургалт үүсгэнэ",
  "Хувирсан плагиоклаз, хувирсан эвэр хуурмаг, мон.пироксены шигтгээнүүд (20-25%) ба плагиоклаз, хувирсан эвэр хуурмаг, цөөн кварцаас тогтсон офитлог, пойкилоофитлог үндсэн хэсгээс бүрдэнэ. Мон.пироксены шигтгээ (1.0-2.0 мм) хувираагүй, захаасаа хувирсан эвэр хуурмагаар эмжээрлэгдсэн. Чулуунд кварц, карбонатаас тогтсон 0.1-8.0 мм өргөнтэй линз, судлууд үүсч, тэдгээрийн дунд хүдэржилт явагдсан. Энэ порфир дотор (009-149.5 дээжтэй ижилхэн) жижиг-дунд ширхэгтэй эвэр хуурмагт габбродиоритын 10-30 мм шлирүүд 20-25% хэмжээтэй ажиглагдана. Ойсон гэрэлд ильменит, пирит, халькопирит тодорхойлогдов."),
 ("41023","OVD009","151.6 m","1obtPlYrPnq9Wqp51W5SZr5CO4vOjZy7T",
  "Porphyritic fine-grained pyroxene-hornblende gabbro (altered gabbro porphyry)",
  "Шигтгээ маягийн жижиг ширхэгтэй пироксен-эвэр хуурмагт габбро (Хувирсан габбро порфир)",
  "Структур: шигтгээлэг, үнд.х-субофитлог, пойкилоофитлог, призмлэг мөхлөгт. Текстур: цул нягт. Шигтгээ 1.0-2.5 мм, үндсэн хэсэг 0.2-0.8 мм",
  [{"mineral":"Хувирсан плагиоклаз / altered plagioclase","pct":"55-60"},
   {"mineral":"Эвэр хуурмаг / hornblende","pct":"25-30"},
   {"mineral":"Мон.пироксен / clinopyroxene","pct":"5-10"},
   {"mineral":"Кварц / quartz","pct":"цөөн (few)"},
   {"mineral":"Ильменит / ilmenite","pct":"0.5-1"},
   {"mineral":"Пирит / pyrite","pct":"цөөн (few)"},
   {"mineral":"Титанит / titanite","pct":"цөөн (few)"},
   {"mineral":"Халькопирит / chalcopyrite","pct":"0.5"},
   {"mineral":"Пирротин / pyrrhotite","pct":"1-2"},
   {"mineral":"Апатит / apatite","pct":"цөөн (few)"}],
  "Серицит, мусковит, карбонат, хлорит, актинолит, эпидот; эпигенет карбонат, кварц. Плагиоклазын шигтгээ эпидот, мусковит-серицитэт агрегатад хүчтэй хувирсан; эвэр хуурмаг хлорит-актинолитод хүчтэй хувирсан; 0.1-8.0 мм өргөнтэй кварц-карбонатын линз, судлууд",
  "Ильменит-титанит-пирит-халькопирит. Ильменит ягаавтар саарал 0.1-0.5 мм, лейкоксеноор бага хувирсан, халькопиритын 0.01-0.1 мм бичил мөхлөгтэй ургалт; хожуу карбонат-кварцын линз дотор шаргал ягаан пирротин (0.3-4.0 мм) ба халькопиритын ургалтаас тогтсон 3.0х7.0 мм линзүүд, мөн цайвар шар пиритээс тогтсон бичил линзүүд",
  "Энэ чулуу нь ерөнхийдөө OVD009-149.5 ба OVD009-149.8 дээжүүдтэй ижил төстэй бөгөөд мон.пироксен, эвэр хуурмаг, хувирсан плагиоклазын шигтгээнүүд (20-25%) ба плагиоклаз, хувирсан эвэр хуурмагаас тогтсон офитлог, пойкилоофитлог үндсэн хэсгээс бүрдэнэ. Мон.пироксены шигтгээ (1.0-2.5 мм) хувираагүй; эвэр хуурмагийн шигтгээ (1.0-2.0 мм) карбонат, актинолит, хлоритод хувирсан. Ойсон гэрэлд ильменит, пирротин, пирит, халькопирит тодорхойлогдож, хожуу карбонат-кварцын линз дотор пирротин-халькопиритын 3.0х7.0 мм хүртэл ургалт үүссэн байна."),
 ("41017","OVD009","161 m","1gQUNPeXL6LnbQ-zuuAElk2uUcTVpstUx",
  "Mineralized, altered porphyritic medium- to fine-grained melanocratic gabbronorite (peridotite?)",
  "Хүдэржиж, хувирсан шигтгээ маягийн дунд жижиг ширхэгтэй меланократ габбронорит (Перидотит?)",
  "Структур: шигтгээ маягийн, үнд.х-субофитлог, пойкилоофитлог. Текстур: цул нягт. Шигтгээ 1.0-6.0 мм, үндсэн хэсэг 0.1-0.8 мм",
  [{"mineral":"Хувирсан пироксен / altered pyroxene (bastite)","pct":"10-15"},
   {"mineral":"Хувирсан плагиоклаз / altered plagioclase","pct":"5-10"},
   {"mineral":"Эвэр хуурмаг / hornblende","pct":"5"},
   {"mineral":"Хувирсан оливин / altered olivine","pct":"5-8"},
   {"mineral":"Биотит / biotite","pct":"10-15"},
   {"mineral":"Халькопирит / chalcopyrite","pct":"1-2"},
   {"mineral":"Пирротин / pyrrhotite","pct":"0.5-1.0"},
   {"mineral":"Ильменит / ilmenite","pct":"цөөн (few)"},
   {"mineral":"Магнетит / magnetite","pct":"цөөн (few)"},
   {"mineral":"Пентландит / pentlandite","pct":"цөөн (few)"},
   {"mineral":"Хромит / chromite","pct":"цөөн (few)"},
   {"mineral":"Сфалерит / sphalerite (?)","pct":"ганц нэг (rare)"}],
  "Серицит, карбонат, хлорит, актинолит, серпентин, тальк. Ромбо пироксен баститад (лизардит-серпентин) бүрэн псевдоморфоз болтлоо хувирсан; оливин серпентинд бүрэн хувирсан; плагиоклаз серицитэд хүчтэй хувирсан",
  "Магнетит-ильменит-хромит-пентландит-пирротин-халькопирит. Пирротин-халькопиритын ургалтаас тогтсон 2.0-8.0 мм линзүүд чулуунд 15-20%; линз захаар пентландит (0.1-0.2 мм) ба ильменит; ильменит 0.1-0.5 мм лейкоксентэй; магнетит 0.1-0.3 мм ба серпентины судланцрын дагуу 0.01-0.1 мм; хромит 0.02-0.1 мм; халькопиритын тоосонцор агуулсан сфалерит(?) 0.1-0.2 мм",
  "Пироксен, хувирсан оливин, хувирсан эвэр хуурмагийн шигтгээ маягийн ялгарлууд (60-65%) ба плагиоклаз, хувирсан эвэр хуурмаг, хувирсан пироксен, биотитоос тогтсон үндсэн хэсгээс бүрдэнэ. Хувирсан ромбо пироксены шигтгээ (1.0-6.0 мм) баститад бүрэн псевдоморфоз болж, ногоон серпентины нарийхан судлуудаар зүсэгдэн түүнийг даган хүдрийн эрдсийн бичил мөхлөгүүд (0.01-0.03 мм) үүссэн. Бараг хувиралд өртөөгүй моноклин пироксен, серпентинд бүрэн хувирсан оливины псевдоморфоз (2.5-3.0 мм) ажиглагдана. Ойсон гэрэлд ильменит, магнетит, пирротин, пентландит, хромит, халькопирит тодорхойлогдож, пирротин-халькопиритын линзүүд чулуунд 15-20%-ийг эзэлнэ."),
 ("41016","OVD009","171.5 m","180rRCCwZYjQjBI-sK_DFmbwoGK8vhcyN",
  "Mineralized altered fine- to medium-grained melanocratic gabbronorite (peridotite?)",
  "Хүдэржсэн жижиг дунд ширхэгтэй хувирсан меланократ габбронорит (перидотит?)",
  "Структур: панидиоморфлог, пойкилоофитлог, пойкилитлог. Текстур: цул нягт. Эрдсийн мөхлөг 0.3-5.0 мм",
  [{"mineral":"Хувирсан пироксен / altered pyroxene (ortho + clino)","pct":"40-45"},
   {"mineral":"Хувирсан оливин / altered olivine","pct":"15-20"},
   {"mineral":"Эвэр хуурмаг / hornblende","pct":"10-15"},
   {"mineral":"Хувирсан плагиоклаз / altered plagioclase","pct":"10"},
   {"mineral":"Биотит / biotite","pct":"1-3"},
   {"mineral":"Халькопирит / chalcopyrite","pct":"8-10"},
   {"mineral":"Пирротин / pyrrhotite","pct":"10-15"},
   {"mineral":"Ильменит / ilmenite","pct":"1-2"},
   {"mineral":"Магнетит / magnetite","pct":"1-2"},
   {"mineral":"Пентландит / pentlandite","pct":"1-3"},
   {"mineral":"Хромит / chromite","pct":"цөөн (few)"}],
  "Серицит, карбонат, хлорит, актинолит, серпентин, тальк(?). Ромбо пироксен хуваагдлын ан цавын дагуу серпентины судлуудаар зүсэгдэж, захаасаа серпентин-актинолитоор түрэгдсэн; оливин серпентин-магнетитын судлаар торлог бүтэц үүсгэсэн; плагиоклаз серицитэд хувирсан",
  "Магнетит-ильменит-хромит-пентландит-пирротин-халькопирит. Пентландит-пирротин-халькопиритын ургалтаас тогтсон 1.0-8.0 мм линзүүд чулууны 30-35%-ийг эзэлнэ; ильменит 0.05-0.5 мм, халькопиритын тоосонцор агуулна; хромит 0.03-0.6 мм; магнетит 0.1-0.3 мм ба серпентины судланцрын дагуу 0.01-0.1 мм; сфалерит линз дотор",
  "Хувирсан пироксен, хувирсан оливин, хувирсан эвэр хуурмаг, бага зэргийн плагиоклаз, биотит ба хүдрийн эрдсүүдээс бүрдэнэ. Ромбо пироксен шулуун унтралтай, мон.пироксен 35-38 градусын унтралтай, 0.3-5.0 мм; оливин зургаа-найман талт 0.2-3.0 мм, хөндлөн ан цавын дагуу серпентин, магнетитын нарийхан судлууд үүсч торлог бүтэц үүсгэсэн. Хүчтэй хүдэржилтийн улмаас пентландит-пирротин-халькопиритын ургалтаас тогтсон 1.0-8.0 мм линзүүд чулууны бараг 30-35%-ийг эзэлж, жигд тархалттай үүссэн байна."),
 ("41034","OVD009","190.8 m","12JXw5FsWuVxKDMeyXnr9YChSdciAmE7b",
  "Mineralized porphyritic fine-grained pyroxene-hornblende gabbro (altered gabbro porphyry)",
  "Хүдэржсэн шигтгээ маягийн жижиг ширхэгтэй пироксен-эвэр хуурмагт габбро /Хувирсан габбро порфир/",
  "Структур: шигтгээлэг, үнд.х-субофитлог, пойкилоофитлог, призмлэг мөхлөгт. Текстур: цул нягт. Шигтгээ 0.8-2.5 мм, үндсэн хэсэг 0.1-0.6 мм",
  [{"mineral":"Хувирсан плагиоклаз / altered plagioclase","pct":"55-60"},
   {"mineral":"Эвэр хуурмаг / hornblende","pct":"30-35"},
   {"mineral":"Мон.пироксен / clinopyroxene","pct":"5-10"},
   {"mineral":"Хувирсан биотит / altered biotite","pct":"цөөн (few)"},
   {"mineral":"Кварц / quartz","pct":"цөөн (few)"},
   {"mineral":"Ильменит / ilmenite","pct":"0.5-1.0"},
   {"mineral":"Пирит / pyrite","pct":"3-5"},
   {"mineral":"Пирротин / pyrrhotite","pct":"цөөн (few)"},
   {"mineral":"Халькопирит / chalcopyrite","pct":"1-3"},
   {"mineral":"Хромит / chromite","pct":"цөөн (few)"},
   {"mineral":"Магнетит / magnetite","pct":"цөөн (few)"},
   {"mineral":"Титанит / titanite","pct":"0.5-1"}],
  "Серицит, пелит, эпидот, хлорит, актинолит, карбонат, лейкоксен, кварц. Плагиоклазын шигтгээ (0.8-2.5 мм) дундлаг-суурилаг найрлагатай, эпидот, серицит, пелитэд хүчтэй хувирсан; эвэр хуурмаг актинолитод бага хувирсан; ан цаваар кварц, карбонатын 0.2-0.6 мм мөхлөгүүд",
  "Ильменит-хромит-титанит-пирит-пирротин-халькопирит. Хүдрийн эрдсээс тогтсон 0.2-3.0 мм өргөнтэй линз, судлууд; ильменит ягаавтар саарал 0.1-0.6 мм, лейкоксенжсэн, халькопиритын 0.01-0.1 мм бичил мөхлөгтэй; пирит зонхилох ба 0.5-1.5 мм өргөнтэй судлууд үүсгэн чулууг зүсэж, халькопиритын бичил мөхлөг агуулна",
  "Хувирсан плагиоклаз, эвэр хуурмагийн шигтгээ маягийн ялгарлууд (40-45%) ба плагиоклаз, эвэр хуурмаг, цөөн мон.пироксеноос тогтсон офитлог, пойкилоофитлог үндсэн хэсгээс бүрдэнэ. Эвэр хуурмагийн шигтгээ (0.8-2.0 мм) бор хүрэн өнгөтэй, дотроо хувираагүй мон.пироксены 0.2-0.4 мм мөхлөг агуулна; мон.пироксен 36-38 градусын унтралтай. Чулуу хүдэржилтэд өртсний улмаас хүдрийн эрдсээс тогтсон 0.2-3.0 мм өргөнтэй линз, судлууд үүсч, хүдрийн эрдсүүд чулууг бүрдүүлэгч эрдсүүдтэй ургалт үүсгэсэн. Ойсон гэрэлд ильменит, магнетит, пирит, хромит, пирротин, халькопирит тодорхойлогдов."),
 ("41014","OVD009","195.2 m","1JizR826XY6q8ymy0RK9o9lDs5yXm-ag2",
  "Mineralized, altered porphyritic fine- to medium-grained melanocratic gabbronorite (peridotite?)",
  "Хүдэржиж, хувирсан шигтгээ маягийн жижиг дунд ширхэгтэй меланократ габбронорит (Перидотит?)",
  "Структур: шигтгээ маягийн, үнд.х-субофитлог, пойкилоофитлог. Текстур: цул нягт. Шигтгээ 0.8-4.0 мм, үндсэн хэсэг 0.1-0.6 мм",
  [{"mineral":"Хувирсан пироксен / altered pyroxene (bastite)","pct":"10-15"},
   {"mineral":"Эвэр хуурмаг / hornblende","pct":"8-10"},
   {"mineral":"Биотит / biotite","pct":"10"},
   {"mineral":"Хувирсан плагиоклаз / altered plagioclase","pct":"1-3"},
   {"mineral":"Хувирсан оливин / altered olivine","pct":"1-3"},
   {"mineral":"Халькопирит / chalcopyrite","pct":"0.5"},
   {"mineral":"Пирротин / pyrrhotite","pct":"0.5-1"},
   {"mineral":"Ильменит / ilmenite","pct":"цөөн (few)"},
   {"mineral":"Магнетит / magnetite","pct":"цөөн (few)"},
   {"mineral":"Хромит / chromite","pct":"цөөн (few)"},
   {"mineral":"Пентландит / pentlandite","pct":"цөөн (few)"}],
  "Серпентин, тальк, мусковит, серицит, хлорит, актинолит, карбонат. Ромбо пироксен баститад (лизардит-серпентин) бүрэн псевдоморфоз болтлоо хувирсан; баститын псевдоморфоз гадуураа актинолит, хлоритжсон биотит, тальк агрегатаар түрэгдсэн; плагиоклаз серицитэд хүчтэй хувирсан",
  "Магнетит-ильменит-хромит-пирротин-халькопирит. Пирротин-халькопиритын ургалтаас тогтсон 0.8-3.0 мм линзүүд чулуунд 10-15%, гадуураа хожуу карбонатаар эмжээрлэгдсэн; магнетит 0.1-0.4 мм ба серпентины судланцрын дагуу 0.01-0.1 мм; ильменит 0.1-0.5 мм биотит, хувирсан эвэр хуурмагтай ассоциацитай; хромит 0.02-0.1 мм бөөгнөрсөн",
  "Энэ чулуу нь ерөнхийдөө OVD009-161 дээжтэй ижилхэн бөгөөд пироксен, хувирсан оливин, хувирсан эвэр хуурмагийн шигтгээ маягийн ялгарлууд (60-65%) ба актинолитжсон эвэр хуурмаг, серпентинжсэн пироксен, бага зэргийн хувирсан плагиоклаз, биотитоос тогтсон хүчтэй хувирсан үндсэн хэсгээс бүрдэнэ. Хувирсан ромбо пироксены шигтгээ (0.8-4.0 мм) баститад бүрэн псевдоморфоз болж реликт призмлэг хэлбэрээ хадгалсан. Ойсон гэрэлд ильменит, магнетит, пирротин, пентландит, хромит, халькопирит тодорхойлогдож, пирротин-халькопиритын 0.8-3.0 мм линзүүд чулуунд 10-15%-ийг эзэлнэ."),
]
for tag, hole, depth, pdfid, rock_en, rock_mn, tex, mins, alt, opq, summ in K:
    recs.append(R(source_file=SF, source_fileId=FID, sample_id=tag,
        drillhole_id=hole, depth=depth,
        sample_type="polished thin section (ӨТШ); section header 'ӨТШ-" + hole + "-" + depth.split(" ")[0] +
                    "'; per-sample PDF " + tag + ".pdf fileId " + pdfid,
        rock_name=rock_en, rock_name_original=rock_mn, texture=tex,
        minerals=mins, alteration=alt, opaque_minerals=opq,
        description_summary=summ, analyst_or_lab=LAB, report_date=None))

# ================================================================ D  ARDH-2005-01 photo-only stubs
SF = "CORE PHOTO/ARDH-2005-01/4. Thin section photo (folder - JPG images only, no accompanying report)"
FID = "folder:1SpY0E3wPZudd9e6KIC5D8SpFgfnRF2tk"
ARDH = [("DSC00228","1vYYemys2Ff_RuyG3mXvUb4-poYrMQ1Hx","2005-11-09"),
        ("DSC00229","1Ld-HDjowwKZMjgDxqxCrEwcNSc2WJ-VO","2005-11-09"),
        ("DSC00230","14ZTmklnu5i_KsSrfQadyuCWtlnSJWa0N","2005-11-09"),
        ("DSC00231","13RXgi1Y9H7r0_EhEjUQHYTuhK0pyoRZc","2005-11-09"),
        ("DSC00232","1Zk6yPLjQzzO4vUQ_G6hnLay2-9192hUi","2005-11-09"),
        ("DSC00233","1_DzfiTQDnE580BZos3IXPORzcV1DyzwX","2005-11-09"),
        ("DSC00234","16oJ5d7udM-qCkQBa80DHnLgk9pda3zA2","2005-11-09"),
        ("DSC00235","1DK3GgXyEERepSh4wdwDRtvau_rKG6K_J","2005-11-09"),
        ("DSC00251","1lg_O5TwsNdZ5LRFAST-UpKtR948tPfFT","2005-11-10"),
        ("DSC00252","1tWEVEDJrpaVIKVrqfK36kKtK7BIvrO3-","2005-11-10"),
        ("DSC00253","1UvsKe57PUjKXRWN1vQgwOC-WWpif58u8","2005-11-10"),
        ("DSC00254","1LAHQOgtw3j3ChGjwurT2KoM9WAZDXFPb","2005-11-10"),
        ("DSC00255","1UwvCJUert0xsQnkyn33Y-CjeUXR9QKXv","2005-11-10"),
        ("DSC00257","1dECwdgQj0yF2nt7w-p_OCttwwZignfIB","2005-11-10"),
        ("DSC00258","1_CMHvIjca7GPk3aYZupzd9-UAcuUThKR","2005-11-10"),
        ("DSC00259","18K8jMTcHzK4pT0Fc9U8q4oQmmzkOTW8W","2005-11-10"),
        ("DSC00260","1InTZ2OQTK27hcPFZtbAXkgb2ImM3p1-n","2005-11-10")]
for name, fid, dt in ARDH:
    recs.append(R(source_file=SF + " :: " + name + ".JPG", source_fileId=fid,
        sample_id=name, drillhole_id="ARDH-2005-01", depth=None,
        sample_type="thin section photograph only (photo_only) - no petrographic text found; filename is a camera sequence number, not a sample/lab tag",
        rock_name=None, rock_name_original=None, texture=None, minerals=[], alteration=None,
        opaque_minerals=None,
        description_summary="Photo-only record. The ARDH-2005-01 'CORE PHOTO/4. Thin section photo' folder holds 18 JPG files (17 unique; 'Copy of DSC00233.JPG' duplicates DSC00233). No petrographic or mineragraphic report, spreadsheet or description document accompanies them anywhere in the ARDH-2005-01 tree (sibling folders are only '1. Hole Location photo', '2. Core photo' and '3. Speciment photo'). File EXIF/modified dates are 2005-11-09 and 2005-11-10, consistent with the 2005 ARDH drilling campaign. Sample identity must be resolved from an external ARDH-2005-01 sample register - the filenames carry no sample number.",
        analyst_or_lab=None, report_date=dt))

path = os.path.join(OUT, "samples.json")
old = json.load(open(path, encoding="utf-8"))
old.extend(recs)
json.dump(old, open(path, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("batch2 records:", len(recs), "total:", len(old))
