// Default code libraries (pick lists).
//
// LITH = AZ9 Maikhan Uul Lithology Code Standard v4 (2026-09-23): the 34 codes
// already in MX Deposit's Lith1 list + FRHYF / SCHRF. Codes and groups follow the
// standard; meanings marked `verify` were not in the source available when this
// file was written — confirm them against MU_Lithology_Codes_v4.xlsx, or import
// that list on the Code lists page (import replaces meanings/colours by code).
//
// ALT = the MX "A-codes" still used in MX Deposit (Alt1-3). AltCode v1 (photo log)
// is deliberately not loaded here, matching the current MX practice.

const L = (code, group, en, mn, color, extra = {}) => ({ code, group, meaning: en, meaningMn: mn, color, ...extra });

export const LITH_V4 = [
  L('COLL', '1 Cover', 'Colluvium', 'Колюви', '#c9b48a'),
  L('TSL', '1 Cover', 'Topsoil / surface cover', 'Хөрс, гадаргын хучаас', '#8b6b45', { verify: true }),
  L('SGRT', '1 Cover', 'Sand–gravel regolith', 'Элс-хайрга', '#d8c9a3', { verify: true }),
  L('FRHY', '2 Felsic volcanic – coherent', 'Rhyolite', 'Риолит', '#efb3c4'),
  L('SCHR', '2 Felsic volcanic – coherent', 'Schistose rhyolite', 'Занарлаг риолит', '#d79bb4', { verify: true }),
  L('RHD', '2 Felsic volcanic – coherent', 'Rhyodacite', 'Риодацит', '#e3a19c'),
  L('FDAC', '2 Felsic volcanic – coherent', 'Dacite', 'Дацит', '#c48dad'),
  L('FRHYF', '3 Fe-oxide halo', 'Rhyolite, pervasive Fe-oxide (Int H–I, ≥50 %)', 'Риолит, Fe-ислийн хүрээ', '#cf6a4c', { mxPending: true, mxFallback: 'FRHY' }),
  L('SCHRF', '3 Fe-oxide halo', 'Schistose rhyolite, pervasive Fe-oxide', 'Занарлаг риолит, Fe-ислийн хүрээ', '#b5553e', { mxPending: true, mxFallback: 'SCHR' }),
  L('FRHTF', '4 Volcaniclastic', 'Rhyolitic tuff', 'Риолитын туф', '#f3d2a5'),
  L('SCHTR', '4 Volcaniclastic', 'Schistose rhyolitic tuff', 'Занарлаг риолитын туф', '#e4bf8d', { verify: true }),
  L('FDACTF', '4 Volcaniclastic', 'Dacitic tuff', 'Дацитын туф', '#d6ae7a'),
  L('FT', '4 Volcaniclastic', 'Felsic tuff', 'Хүчиллэг туф', '#e8d6ad'),
  L('ILT', '4 Volcaniclastic', 'Lapilli tuff', 'Лапилли туф', '#c2af88', { verify: true }),
  L('IAND', '5 Intermediate / mafic, dykes', 'Andesite', 'Андезит', '#6f9a6b'),
  L('MT', '5 Intermediate / mafic, dykes', 'Unconfirmed meaning – do not use', 'Утга тодорхойгүй – бүү ашигла', '#4f7a55', { warn: true }),
  L('IDI', '5 Intermediate / mafic, dykes', 'Diorite', 'Диорит', '#7c9c8b'),
  L('MBP', '5 Intermediate / mafic, dykes', 'Basaltic porphyry dyke', 'Базальтын порфир дайк', '#3e5b47', { verify: true }),
  L('CMSQ', '6 Silica body & breccia', 'Silica body (vuggy/massive; Al<1 %, S<5 %)', 'Цахиурын биет', '#e6ecf1'),
  L('BRQ', '6 Silica body & breccia', 'Quartz breccia', 'Кварцын брекчи', '#bcd0e4'),
  L('HYBR', '6 Silica body & breccia', 'Hydrothermal breccia', 'Гидротермал брекчи', '#8da7c6'),
  L('MSUL', '7 Sulphide & gossan', 'Massive sulphide (>50 %)', 'Массив сульфид (>50 %)', '#c9a227'),
  L('VMS', '7 Sulphide & gossan', 'Semi-massive sulphide (10–50 %)', 'Хагас массив сульфид (10–50 %)', '#dcbc50'),
  L('VSU', '7 Sulphide & gossan', 'Sulphide vein', 'Сульфидын судал', '#b38e37', { verify: true }),
  L('GOS', '7 Sulphide & gossan', 'Gossan (after sulphide only)', 'Госсан', '#8c3b1f'),
  L('VQZ', '8 Vein (>50 % of interval)', 'Quartz vein', 'Кварцын судал', '#f4f3ea'),
  L('VQS', '8 Vein (>50 % of interval)', 'Quartz–sulphide vein', 'Кварц-сульфидын судал', '#d9dec4'),
  L('VQBR', '8 Vein (>50 % of interval)', 'Quartz vein breccia', 'Кварцын судлын брекчи', '#c5cedb'),
  L('VQH', '8 Vein (>50 % of interval)', 'Quartz–hematite vein', 'Кварц-гематитын судал', '#b7897d', { verify: true }),
  L('BFZ', '9 Fault & breccia', 'Fault zone', 'Хагарлын бүс', '#7b7b80'),
  L('BFG', '9 Fault & breccia', 'Fault gouge', 'Хагарлын шавар (gouge)', '#4d4d52'),
  L('BSZ', '9 Fault & breccia', 'Shear zone', 'Зүсэлтийн бүс', '#8e8ea0'),
  L('BR', '9 Fault & breccia', 'Breccia', 'Брекчи', '#a6a6ab'),
  L('BRT', '9 Fault & breccia', 'Tectonic breccia', 'Тектоник брекчи', '#95959b', { verify: true }),
  L('CBX', '9 Fault & breccia', 'Crackle breccia', 'Хагархай брекчи', '#b7b7bc'),
  L('CL', '10 Technical', 'Core loss', 'Кернгүй', '#1b1b1f'),
];

const simple = (pairs, group = '') =>
  pairs.map(([code, en, mn, color], i) => ({ code, meaning: en, meaningMn: mn ?? en, color: color ?? '', group, order: i }));

export const DEFAULT_LISTS = {
  LITH: LITH_V4,
  ALT: simple([
    ['ASIL', 'Silicification', 'Цахиуржилт', '#9fb8d0'],
    ['ASER', 'Sericite', 'Серицитжилт', '#d9cf8a'],
    ['ACHL', 'Chlorite', 'Хлоритжилт', '#5f8f5a'],
    ['AEPI', 'Epidote', 'Эпидотжилт', '#8faa4a'],
    ['ACAR', 'Carbonate', 'Карбонатжилт', '#d6d2c4'],
    ['AKLN', 'Kaolinite', 'Каолинжилт', '#f1ede2'],
    ['AALU', 'Alunite', 'Алунитжилт', '#e8d7e8'],
    ['ACLY', 'Clay (undifferentiated)', 'Шаварлаг хувирал', '#e2d5bd'],
    ['AHEM', 'Hematite', 'Гематит', '#a23b2a'],
    ['ALIM', 'Limonite', 'Лимонит', '#c98a2e'],
    ['AGOE', 'Goethite', 'Гётит', '#9c6a2a'],
    ['AJAR', 'Jarosite', 'Ярозит', '#d4b43c'],
    ['ASHE', 'Fe-oxide (verify meaning in MX list)', 'Fe-исэл (утгыг MX-ээс шалга)', '#b0583a'],
    ['ALIC', 'Fe-oxide (verify meaning in MX list)', 'Fe-исэл (утгыг MX-ээс шалга)', '#c07a3a'],
    ['ALIS', 'Fe-oxide (verify meaning in MX list)', 'Fe-исэл (утгыг MX-ээс шалга)', '#c68d4a'],
    ['ALIP', 'Fe-oxide (verify meaning in MX list)', 'Fe-исэл (утгыг MX-ээс шалга)', '#b8773c'],
    ['AHGO', 'Unconfirmed meaning – do not use', 'Утга тодорхойгүй – бүү ашигла', '#8a5a3a'],
    ['APOT', 'Potassic', 'Калижилт', '#e39a8f'],
    ['APRP', 'Propylitic', 'Пропилитжилт', '#7fa37a'],
  ]).map((c) => (c.code === 'AHGO' ? { ...c, warn: true } : c)),
  INT: simple([
    ['W', 'Weak', 'Сул'],
    ['M', 'Moderate', 'Дунд'],
    ['S', 'Strong', 'Хүчтэй'],
    ['H', 'Very strong', 'Маш хүчтэй'],
    ['I', 'Intense / pervasive', 'Бүрэн (нэвчимтгий)'],
  ]),
  STYLE: simple([
    ['PER', 'Pervasive', 'Нэвчимтгий'],
    ['SEL', 'Selective', 'Сонгомол'],
    ['PAT', 'Patchy', 'Толбот'],
    ['FRC', 'Fracture-controlled', 'Ан цаваар'],
    ['VNL', 'Veinlet / halo', 'Судалцар, хүрээ'],
    ['DIS', 'Disseminated', 'Цацмал'],
    ['BLB', 'Blebby', 'Бөөгнөрөл'],
    ['STK', 'Stockwork', 'Штокверк'],
    ['SMS', 'Semi-massive', 'Хагас массив'],
    ['MAS', 'Massive', 'Массив'],
  ]),
  WEATH: simple([
    ['1', 'Soil / completely weathered (COLL)', 'Хөрс / бүрэн өгөршсөн'],
    ['2', 'Highly weathered', 'Хүчтэй өгөршсөн'],
    ['3', 'Moderately weathered', 'Дунд зэрэг өгөршсөн'],
    ['4', 'Slightly weathered', 'Бага өгөршсөн'],
    ['5', 'Stained joints only', 'Зөвхөн ан цав будагдсан'],
    ['6', 'Fresh', 'Шинэлэг'],
  ]),
  HARD: simple([
    ['1', 'Very soft (gouge, soil)', 'Маш зөөлөн'],
    ['2', 'Soft', 'Зөөлөн'],
    ['3', 'Medium', 'Дунд'],
    ['4', 'Hard', 'Хатуу'],
    ['5', 'Very hard (silicified)', 'Маш хатуу'],
    ['6', 'Extremely hard (Q-body, VMS)', 'Онцгой хатуу'],
  ]),
  SHADE: simple([
    ['L', 'Light', 'Цайвар'],
    ['M', 'Medium', 'Дунд'],
    ['D', 'Dark', 'Бараан'],
  ]),
  COLOUR: simple([
    ['WHT', 'White', 'Цагаан', '#f4f4f0'],
    ['GRY', 'Grey', 'Саарал', '#9a9a9a'],
    ['BLK', 'Black', 'Хар', '#222222'],
    ['CRM', 'Cream', 'Цөцгий', '#efe3c4'],
    ['BGE', 'Beige', 'Шаргал', '#d8c7a4'],
    ['BRN', 'Brown', 'Бор', '#7a5234'],
    ['RED', 'Red', 'Улаан', '#a3312a'],
    ['PNK', 'Pink', 'Ягаан', '#e6a4b4'],
    ['ORG', 'Orange', 'Улбар шар', '#d9822b'],
    ['YEL', 'Yellow', 'Шар', '#d9c23c'],
    ['GRN', 'Green', 'Ногоон', '#4f8a4b'],
    ['BLU', 'Blue', 'Цэнхэр', '#4a6fa5'],
    ['PUR', 'Purple', 'Нил ягаан', '#7a4a8a'],
  ]),
  GRAIN: simple([
    ['APH', 'Aphanitic', 'Нарийн (афанит)'],
    ['VF', 'Very fine', 'Маш нарийн'],
    ['F', 'Fine', 'Нарийн'],
    ['M', 'Medium', 'Дунд'],
    ['C', 'Coarse', 'Бүдүүн'],
    ['VC', 'Very coarse', 'Маш бүдүүн'],
  ]),
  TEXTURE: simple([
    ['MAS', 'Massive', 'Массив'],
    ['CLA', 'Clastic (tuff) – not clay', 'Хэмхдэслэг (туф)'],
    ['FRG', 'Fragmental', 'Хэлтэрхийлэг'],
    ['POR', 'Porphyritic', 'Порфир'],
    ['FLB', 'Flow-banded', 'Урсгалын зурвастай'],
    ['LAM', 'Laminated', 'Нимгэн үелэг'],
    ['AMY', 'Amygdaloidal', 'Бадамлаг'],
    ['BRX', 'Brecciated', 'Брекчижсэн'],
    ['VUG', 'Vuggy', 'Хөндийлэг'],
  ]).map((c) => (c.code === 'VUG' ? { ...c, mxPending: true } : c)),
  STRUCT: simple([
    ['MAS', 'Massive', 'Массив'],
    ['FOL', 'Foliated', 'Фолиацитай'],
    ['SHR', 'Sheared', 'Зүсэгдсэн'],
    ['FAU', 'Faulted', 'Хагарлын'],
    ['FRC', 'Fractured', 'Ан цавтай'],
    ['BED', 'Bedded', 'Үелэг'],
    ['VEN', 'Veined', 'Судалтай'],
    ['BRK', 'Broken', 'Бутарсан'],
  ]),
  STRINT: simple([
    ['W', 'Weak', 'Сул'],
    ['M', 'Moderate', 'Дунд'],
    ['S', 'Strong', 'Хүчтэй'],
  ]),
  VEINSTYLE: simple([
    ['SGL', 'Single vein', 'Ганц судал'],
    ['SHV', 'Sheeted', 'Хавтгайлаг'],
    ['STK', 'Stockwork', 'Штокверк'],
    ['BRX', 'Breccia infill', 'Брекчийн цемент'],
    ['CRK', 'Crackle', 'Хагархай'],
  ]),
  STRTYPE: simple([
    ['FLT', 'Fault', 'Хагарал'],
    ['SHR', 'Shear', 'Зүсэлт'],
    ['JNT', 'Joint', 'Ан цав'],
    ['VN', 'Vein', 'Судал'],
    ['FOL', 'Foliation', 'Фолиаци'],
    ['BED', 'Bedding', 'Үе'],
    ['CNT', 'Contact', 'Контакт'],
    ['FRC', 'Fracture', 'Хагарц'],
  ]),
  SAMPTYPE: simple([
    ['PRIM', 'Primary', 'Үндсэн', '#6b7a78'],
    ['CRM', 'Certified reference material', 'Стандарт (CRM)', '#c98a12'],
    ['BLK', 'Blank', 'Хоосон (blank)', '#4a6fa5'],
    ['FDUP', 'Field duplicate (¼ core)', 'Хээрийн давхар', '#8a4a8a'],
    ['CDUP', 'Coarse reject duplicate', 'Бутлагдсан давхар', '#a0588a'],
    ['PDUP', 'Pulp duplicate', 'Нунтаг давхар', '#b56a9a'],
    ['PETRO', 'Petrography / specimen sample', 'Петрографийн дээж', '#5b7fa5'],
  ]),
  HOLETYPE: simple([
    ['DD', 'Diamond core', 'Керн өрөмдлөг'],
    ['RC', 'Reverse circulation', 'RC'],
    ['RCD', 'RC pre-collar + diamond tail', 'RC + керн'],
    ['AC', 'Aircore', 'Aircore'],
    ['RAB', 'Rotary air blast', 'RAB'],
    ['TR', 'Trench', 'Шуудуу'],
  ]),
  HOLESTATUS: simple([
    ['PLN', 'Planned', 'Төлөвлөсөн', '#8a94a6'],
    ['ACT', 'Drilling', 'Өрөмдөж буй', '#c98a12'],
    ['CMP', 'Completed', 'Дууссан', '#2e8b57'],
    ['ABD', 'Abandoned', 'Орхисон', '#c2412d'],
    ['NAC', 'Not accepted', 'Хүлээн аваагүй', '#7a4a8a'],
  ]),
  SURVMETHOD: simple([
    ['PLN', 'Planned (collar design)', 'Төлөвлөсөн'],
    ['CMP', 'Compass / clinometer', 'Компас'],
    ['SS', 'Single shot', 'Single shot'],
    ['MS', 'Multi shot', 'Multi shot'],
    ['GYR', 'Gyro', 'Гиро'],
    ['EZT', 'Reflex EZ-Trac', 'EZ-Trac'],
    ['DGPS', 'DGPS / RTK collar', 'DGPS / RTK'],
    ['GM', 'GM (as recorded in source – verify)', 'GM (эх сурвалжийнхаар – шалга)'],
    ['GY', 'GY (as recorded in source – verify)', 'GY (эх сурвалжийнхаар – шалга)'],
  ]),
  CORESIZE: simple([
    ['PQ', 'PQ (85 mm)', 'PQ'],
    ['HQ', 'HQ (63.5 mm)', 'HQ'],
    ['HQ3', 'HQ3 (61.1 mm)', 'HQ3'],
    ['NQ', 'NQ (47.6 mm)', 'NQ'],
    ['NQ2', 'NQ2 (50.6 mm)', 'NQ2'],
    ['BQ', 'BQ (36.4 mm)', 'BQ'],
  ]),
};

export const LIST_NAMES = {
  LITH: { en: 'Lithology (Lith1) – MU v4', mn: 'Литологи (Lith1) – MU v4' },
  ALT: { en: 'Alteration (MX A-codes)', mn: 'Хувирал (MX A-код)' },
  INT: { en: 'Intensity', mn: 'Эрчим' },
  STYLE: { en: 'Style', mn: 'Хэлбэр' },
  WEATH: { en: 'Weathering', mn: 'Өгөршил' },
  HARD: { en: 'Hardness', mn: 'Хатуулаг' },
  SHADE: { en: 'Shade', mn: 'Өнгөний гэгээ' },
  COLOUR: { en: 'Colour', mn: 'Өнгө' },
  GRAIN: { en: 'Grain size', mn: 'Ширхэглэл' },
  TEXTURE: { en: 'Texture', mn: 'Текстур' },
  STRUCT: { en: 'Structure', mn: 'Бүтэц' },
  STRINT: { en: 'Structure intensity', mn: 'Бүтцийн эрчим' },
  VEINSTYLE: { en: 'Vein style', mn: 'Судлын хэлбэр' },
  STRTYPE: { en: 'Structure type (measurements)', mn: 'Бүтцийн хэмжилтийн төрөл' },
  SAMPTYPE: { en: 'Sample type', mn: 'Дээжийн төрөл' },
  HOLETYPE: { en: 'Hole type', mn: 'Цооногийн төрөл' },
  HOLESTATUS: { en: 'Hole status', mn: 'Цооногийн төлөв' },
  SURVMETHOD: { en: 'Survey method', mn: 'Хэмжилтийн арга' },
  CORESIZE: { en: 'Core size', mn: 'Кернийн диаметр' },
};

/** Default project settings. Everything here is editable on the Settings page. */
export function defaultSettings() {
  return {
    crs: 'WGS84 / UTM zone 46N',
    epsg: 32646,
    dipNegativeDown: true,
    commentsMax: 500, // MX Deposit hard limit
    commentsSoft: 200, // house style
    minSampleLen: 0.3,
    maxSampleLen: 2.0,
    qc: {
      crmEvery: 25,
      blankEvery: 25,
      dupEvery: 20,
      blankOffset: 12,
      dupType: 'FDUP',
      crmRotation: ['OREAS 504c', 'OREAS 235', 'OREAS 621'],
      blankCode: 'BLK-QTZ',
      crmWarnSD: 2,
      crmFailSD: 3,
      blankFactor: 10, // fail when > factor × LOR
      dupHard: { FDUP: 30, CDUP: 20, PDUP: 10 },
      dupPassRate: 90,
    },
    belowDetection: 'half', // 'half' | 'lor' | 'zero' | 'negative'
    elements: {},
    stripElements: ['Au_ppm', 'Cu_pct'],
    chem: {
      alKey: 'Al_pct',
      sKey: 'S_pct',
      cmsqAlMax: 1,
      cmsqSMax: 5,
      sulphideSMin: 5,
    },
    intercepts: { element: 'Au_ppm', cutoff: 0.3, minLen: 2, maxDil: 3, incl: 1.0, secondary: ['Cu_pct', 'Ag_ppm'] },
  };
}
